### DISCUSSION TITLE
I can't create a cluster if using network policies

### DISCUSSION THREAD

**Discussion by astingengo** [OT-CONTAINER-KIT/redis-operator#420] [Q&A]
Hi there,

The nodes.conf file looks same on all servers [leaders and followers]
```
b3629d55b739131f11e99cc15071078cb6717e5a :0@0 myself,master - 0 0 0 connected
vars currentEpoch 0 lastVoteEpoch 0
```
[with ID different, of course]

If I'll leave only my egress rules w/o ingress rules it will work.
I'm giving full access on ingress as well and the rule for that is:
```
...
  - from:
    - namespaceSelector:
        matchLabels:
          name: redis-namespace
      podSelector:
        matchLabels:
          access_redis: "allowed"
```
If I'll use `nc` I can connect to all pods to `6379` and `16379` but the cluster is not working. All my followers will act as masters.
How can I fix this issue [w/o ingress rules will work, but I need it]

Thanks
