### ISSUE TITLE
Incomplete CRDs in latest published helm repository?

### ISSUE THREAD

**Issue by zumbuschms** [OT-CONTAINER-KIT/redis-operator#1000]
**Describe your question**
As we have encountered issues with deletion of PVCs during uninstallation of Redis replication charts using 0.15.1 of the operator, I was searching the current documentation and found the keepAfterDelete option. As that feature was added in 0.16.0, I decided to update the operator to the latest version and downloaded the archive from the helm repo, as our deployment environment doesn't have Internet access (helm pull ot-helm/redis-operator). Checking the downloaded archive, I was not able to find any definitions for keepAfterDelete in the CRDs and when I compared the content of the 0.16.1 download with the 0.15.1 version we had used since September 2023, all files were identical.

Is the new feature not yet available in the published helm charts, although the info announces version 0.17.0 of the operator?

Output of helm show chart ot-helm/redis-operator
```
apiVersion: v2
appVersion: 0.17.0
dependencies:
- alias: certmanager
  condition: certmanager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.12.4
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
home: https://github.com/OT-CONTAINER-KIT/redis-operator
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
maintainers:
- name: iamabhishek-dubey
- name: sandy724
- name: shubham-cmyk
name: redis-operator
sources:
- https://github.com/OT-CONTAINER-KIT/redis-operator
version: 0.16.1

```
**What version of redis-operator are you using?**
chart version: 0.16.1
app version: 0.17.0
