### ISSUE TITLE
ValidationError: unknow field for redisConfig while using latest operator

### ISSUE THREAD

**Issue by abdul90082** [OT-CONTAINER-KIT/redis-operator#1030]
**What version of redis operator are you using?**

redis-operator version: 0.18.0

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**
Selfhosted 
<summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.23.8
</pre>

**What did you do?**

- Downloaded latest version Redis Helm charts from Github
- Redis Operator 0.18.0
- Redis Replication 0.16.0
- Redis Sentinel 0.16.1
- deployed Redis Replication helm chart
- deployed Redis Sentinel helm chart

**What did you expect to see?**

- working deployment
- deployment without warnings

**What did you see instead?**
`Error: error validating "": error validating data: ValidationError(RedisReplication.spec.redisExporter): unknown field "redisConfig" in in.opstreelabs.redis.redis.v1beta2.RedisReplication.spec.redisExporter`

**Proposed Fix**
fixes identation error for external config because these are on wrong level.
`  redisConfig:
      additionalRedisConfig: "{{ .Values.redisReplication.name | default .Release.Name }}-ext-config"`

**Comment by abdul90082** [comment]
@shubham-cmyk Can i create PR for this because we just need to remove two indentaion?

**Comment by drivebyer** [comment]
@abdul90082  Please try Redis Replication 0.16.1

**Comment by abdul90082** [comment]
@drivebyer Still getting the same error while using the Redis Replication v0.16.1.
`Error: error validating "": error validating data: ValidationError(RedisSentinel.spec.redisExporter): unknown field "redisConfig" in in.opstreelabs.redis.redis.v1beta2.RedisSentinel.spec.redisExporter`

Here is my reids_sentinel.yaml
```
redisSentinel:
  resources: 
    requests:
      cpu : 1m
      memory: 1Mi
    limits:
      memory: 256Mi

externalConfig:
  enabled: true

redisExporter:
  enabled: false
  redisConfig:
    enabled: false
nodeSelector:
  deploy/dbs: "true"
  ```
  
  Here is my reids_replication.yaml
  ```
redisReplication:
  resources: 
     requests:
       cpu : 1m
       memory: 1Mi
     limits:
       memory: ${memory}Gi
     ignoreAnnotations: 
       - "redis.opstreelabs.in/ignore"

externalConfig:
  enabled: true
  data: |
    appendonly ${appendonly}
    save "${save}"
    %{ for key, value in extra_config ~}
    ${key} ${value}
    %{ endfor ~}

nodeSelector:
  deploy/dbs: "true"
  ```

**Comment by drivebyer** [comment]
That's weird. This command works for me: `helm install rr-1 ot-helm/redis-replication --version 0.16.1 --set externalConfig.enabled=true` @abdul90082.

**Comment by abdul90082** [comment]
@drivebyer Redis-replication is also working fine for me, the error is now in redisSentinel, need to fixes identation for redisConfig because this is still on the wrong level [here.](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/charts/redis-sentinel/templates/redis-sentinel.yaml#L59)

**Comment by drivebyer** [comment]
I got you. There is not `redisConfig` field in RedisSentinel spec, we should remove it.

**Comment by abdul90082** [comment]
@drivebyer Thanks for your quick response, after using redisSentinel version 0.16.2 and redisReplication version 0.16.1 getting this error.
`Error: error validating "": error validating data: ValidationError(RedisSentinel.spec.kubernetesConfig): unknown field "minReadySeconds" in in.opstreelabs.redis.redis.v1beta2.RedisSentinel.spec.kubernetesConfig
` 
Here is the resis_sentinel.yaml file
```
redisSentinel:
  resources: 
    requests:
      cpu : 1m
      memory: 1Mi
    limits:
      memory: 256Mi

externalConfig:
  enabled: true

redisExporter:
  enabled: false
```

**Comment by drivebyer** [comment]
@abdul90082  Please apply the [latest CRD file](https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/charts/redis-operator/crds) in your cluster

**Comment by abdul90082** [comment]
@drivebyer I am still getting the error in redis-sentinel setup.
`+sdown master xyz-redis-persistent 10.40.220.24 6379` in the xyz-redis-persistent-sentinel-sentinel-2

k describe pod xyz-redis-persistent-sentinel-sentinel-2 -n xyz-databases
 ` Warning  Unhealthy  7s (x7 over 4m7s)      kubelet            Liveness probe failed: command "sh -c redis-cli -h $(hostname) -p ${SENTINEL_PORT} ping" timed out   `
 
 This is working fine from cli
 `bash-5.1$ redis-cli -h $(hostname) -p ${SENTINEL_PORT} ping PONG
`
here is my redis_sentinel.yaml file 
```
redisSentinel:
  resources: 
    requests:
      cpu : 1m
      memory: 1Mi
    limits:
      memory: 256Mi

nodeSelector:
  deploy/dbs: "true"

externalConfig:
  enabled: false

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - redis-sentinel
        topologyKey: "kubernetes.io/hostname"

storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
```
 
 here is the redis_replication.yaml file
 ```
 ---
redisReplication:
  resources: 
    requests:
      cpu : 1m
      memory: 1Mi
    limits:
      memory: ${memory}Gi
  ignoreAnnotations: 
    - "redis.opstreelabs.in/ignore"

externalConfig:
  enabled: true
  data: |
    appendonly ${appendonly}
    save "${save}"
    %{ for key, value in extra_config ~}
    ${key} ${value}
    %{ endfor ~}

nodeSelector:
  deploy/dbs: "true"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - redis-sentinel
        topologyKey: "kubernetes.io/hostname"
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
```
If you need anything else for further debug i am happy to provide. Thanks
