### ISSUE TITLE
Container image update of opstree/redis breaking my redis installation

### ISSUE THREAD

**Issue by k4kratik** [OT-CONTAINER-KIT/redis-operator#1077]
someone updated existing tag at 19th Sep 2024 here : 
https://quay.io/repository/opstree/redis?tab=tags

and now my whole redis cluster is in **CrashLoopBackOff** (_Happy Friday to me_)

_not sure why someone would do this to a tag which is meant to be immutable._

errors

```
sed: /node-conf/nodes.conf: No such file or directory
Running without persistence mode
Running without TLS mode
ACL_MODE is not true, skipping ACL file modification
Starting redis service in cluster mode.....

*** FATAL CONFIG FILE ERROR (Redis 6.2.5) ***
Reading the configuration file, at line 18
>>> 'cluster-announce-hostname redis-views-analytics-leader-0'
Bad directive or wrong number of arguments
```

I see `nodes.conf` is present in `/data` dir, so is it a path issue ?

please fix it and don't update existing tags 😢

**Comment by drivebyer** [comment]
@k4kratik  Please set spec.clusterVersion to v6 to solve this problem. like:
```
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  clusterVersion: v6
...
```

**Comment by AlexeeyN** [comment]
I have the same issue. Redis is `v6.2.5` as well. We have `apiVersion: redis.redis.opstreelabs.in/v1beta1` API version and it does not support `clusterVersion: v6`. After upgrading redis operator to `v0.13.0 ` according to the Image Compatibility table and changing the API to `v1beta2` I am getting the following error: 
`no matches for kind "RedisCluster" in version "redis.redis.opstreelabs.in/v1beta2"`

**Comment by drivebyer** [comment]
@AlexeeyN Please upgrade your v1beta1 CRD to the latest.

**Comment by k4kratik** [comment]
@drivebyer Thanks for your answer but It didn't help me :( 

```
sed: /node-conf/nodes.conf: No such file or directory
Running without TLS mode
ACL_MODE is not true, skipping ACL file modification
Starting redis service in cluster mode.....
1:C 24 Sep 2024 02:12:33.491 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Sep 2024 02:12:33.491 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Sep 2024 02:12:33.491 # Configuration loaded
1:M 24 Sep 2024 02:12:33.491 * monotonic clock: POSIX clock_gettime
1:M 24 Sep 2024 02:12:33.492 # Can't open the append-only file: Permission denied
```

**Comment by drivebyer** [comment]
@k4kratik  Please add `cluster-config-file /data/nodes.conf` to you custom configmap.

**Comment by k4kratik** [comment]
got it, for me it solved by adding `podSecurityContext` : 
```
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
```

**Comment by k4kratik** [comment]
Thanks @drivebyer for the promptness, really appreciate it :)

**Comment by k4kratik** [comment]
For anyone else, who is bumping here, this is my working manifest for v6 

```
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: my-redis-cluster
  namespace: my-redis-cluster
spec:
  clusterSize: 3
  clusterVersion: v6
  persistenceEnabled: true
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: redis-secret
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
    nodeConfVolume: true
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
data:
  password: my_password
kind: Secret
metadata:
  name: redis-secret
  namespace: my-redis-cluster
type: Opaque
```
