### ISSUE TITLE
Issue with automatic master failover in Redis cluster using Redis Sentinel (delete master)

### ISSUE THREAD

**Issue by abix5** [OT-CONTAINER-KIT/redis-operator#1094]
redis-operator version: 0.18.0

**Does this issue reproduce with the latest release?**

Yes, the issue reproduces on version 0.18.0.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
</pre></details>

**What did you do?**

I used the following configuration file to deploy Redis Replication and Redis Sentinel:

After applying these configurations, all pods start successfully.
```

---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-replication
  namespace: redis-operator-ot
spec:
  clusterSize: 3
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: redis-sentinel
  namespace: redis-operator-ot
spec:
  clusterSize: 3
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  pdb:
    enabled: false
    minAvailable: 1
  redisSentinelConfig:
    redisReplicationName: redis-replication
  kubernetesConfig:
    image: quay.io/opstree/redis-sentinel:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
```

**What did you expect to see?**

I expected that when the Redis master pod is deleted, the cluster would automatically perform a master re-election, and Redis Sentinel would handle this process correctly without any errors.

**What did you see instead?**

When I deleted the Redis master pod, I received the following error in the logs:

`
{"level":"info","ts":"2024-09-27T17:12:21Z","logger":"controllers.RedisSentinel","msg":"Reconciling opstree redis controller","Request.Namespace":"redis-operator-ot","Request.Name":"redis-sentinel"}
{"level":"error","ts":"2024-09-27T17:12:22Z","logger":"controllers.RedisSentinel","msg":"","Request.Namespace":"redis-operator-ot","Request.Name":"redis-sentinel","error":"no master pods found","stacktrace":"github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.getRedisReplicationMasterIP\n\t/workspace/k8sutils/redis-sentinel.go:331\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.IsRedisReplicationReady\n\t/workspace/k8sutils/redis-replication.go:224\ngithub.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisSentinelReconciler).Reconcile\n\t/workspace/controllers/redissentinel_controller.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
`

The cluster does not recover automatically, and Redis Sentinel cannot find a new master. To bring the cluster out of this state, I have to delete all the pods in RedisReplication simultaneously, after which the cluster reinitializes and starts working again.

Please help me figure out this issue. Maybe I am missing something in the configuration, or there is a bug in the operator when handling master failover.
