### ISSUE TITLE
Can't open or create append-only dir appendonlydir: Permission denied

### ISSUE THREAD

**Issue by aasourav** [OT-CONTAINER-KIT/redis-operator#1115]
when I provide PVC then I face a permission-denied issue

```sh
Can't open or create append-only dir appendonlydir: Permission denied
```

here is my manifest:
```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redisssss
  namespace: mashyaatshafia-dev-ns
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: redisssss-redis-sec
    updateStrategy: {}
  securityContext:
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      metadata: {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: do-block-storage
      status: {}
    volumeMount: {}

```

**Comment by aasourav** [comment]
SOlUTION:
If I provide securityContext (given below) . then it works
```yaml
  securityContext:
    runAsUser: 0
    fsGroup: 2000
```

where I found this solution:
[This Solution from Redis repo helps me to resolve this issue](https://github.com/helm/charts/issues/5041#issuecomment-421608472)
