### ISSUE TITLE
Can't open /node-conf/nodes.conf in order to acquire a lock: Permission denied

### ISSUE THREAD

**Issue by leeworker** [OT-CONTAINER-KIT/redis-operator#1117]
Using the given Redis cluster case, it was found that if the same POD is deleted multiple times, the POD cannot be pulled up. Upon checking the logs, it was found that there is an error message indicating lack of permission.

Defaulted container "rediscluster-global-test-leader" out of: rediscluster-global-test-leader, redis-exporter
sed: /node-conf/nodes.conf: No such file or directory
Running without TLS mode
ACL_MODE is not true, skipping ACL file modification
Starting redis service in cluster mode.....
1:C 30 Oct 2024 09:43:28.513 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 30 Oct 2024 09:43:28.513 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 30 Oct 2024 09:43:28.513 # Configuration loaded
1:M 30 Oct 2024 09:43:28.514 * monotonic clock: POSIX clock_gettime
1:M 30 Oct 2024 09:43:28.514 # Can't open /node-conf/nodes.conf in order to acquire a lock: Permission denied

**Comment by LuizDMM** [comment]
Hey @leeworker. I was facing the same problem as you, debugging my problem here (I'm not a developer in this project and it was my first time running the operator), I found out the problem for me was because of the versions of the images I was using. When I ran with these images: `kubernetesConfig.image: quay.io/opstree/redis:v7.0.15` and `redisExporter.image: quay.io/opstree/redis-exporter:v1.48.0` it just worked. Maybe it has something to do with the versions of the images you're using, just sharing to help anyone else having this problem.

**Comment by obitoquilt** [comment]
You can try to add these config
```yaml
spec:
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
```

**Comment by cybercoder** [comment]
> You can try to add these config
> 
> spec:
>   podSecurityContext:
>     fsGroup: 1000
>     runAsUser: 1000


```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: shared-resources
spec:
  clusterSize: 3
  clusterVersion: v7
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: redis
      key: password
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```
same error
on k3s on alpine linux.
