### ISSUE TITLE
Operator error when update redis-sentinel from 0.16.4 to 0.16.5

### ISSUE THREAD

**Issue by vramperez** [OT-CONTAINER-KIT/redis-operator#1118]
**What version of redis operator are you using?**

```shell
{"level":"info","ts":"2024-10-31T11:47:07Z","logger":"controllers.RedisSentinel","msg":"Reconciling opstree redis controller","Request.Namespace":"internal-develop-ci","Request.Name":"redis-sentinel"}
{"level":"error","ts":"2024-10-31T11:47:07Z","logger":"controller_redis","msg":"Redis statefulset update failed","Request.StatefulSet.Namespace":"internal-develop-ci","Request.StatefulSet.Name":"redis-sentinel-sentinel","error":"StatefulSet.apps \"redis-sentinel-sentinel\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden","stacktrace":"github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.updateStatefulSet\n\t/workspace/k8sutils/statefulset.go:796\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.patchStatefulSet\n\t/workspace/k8sutils/statefulset.go:270\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateOrUpdateStateFul\n\t/workspace/k8sutils/statefulset.go:169\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.RedisSentinelSTS.CreateRedisSentinelSetup\n\t/workspace/k8sutils/redis-sentinel.go:69\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateRedisSentinel\n\t/workspace/k8sutils/redis-sentinel.go:52\ngithub.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisSentinelReconciler).Reconcile\n\t/workspace/controllers/redissentinel_controller.go:59\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-10-31T11:47:07Z","logger":"controllers.RedisSentinel","msg":"Cannot create Sentinel statefulset for Redis","error":"StatefulSet.apps \"redis-sentinel-sentinel\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden","stacktrace":"github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.RedisSentinelSTS.CreateRedisSentinelSetup\n\t/workspace/k8sutils/redis-sentinel.go:81\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateRedisSentinel\n\t/workspace/k8sutils/redis-sentinel.go:52\ngithub.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisSentinelReconciler).Reconcile\n\t/workspace/controllers/redissentinel_controller.go:59\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-10-31T11:47:07Z","logger":"controllers.RedisSentinel","msg":"requeue with error","Request.Namespace":"internal-develop-ci","Request.Name":"redis-sentinel","error":"StatefulSet.apps \"redis-sentinel-sentinel\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden","stacktrace":"github.com/OT-CONTAINER-KIT/redis-operator/pkg/controllerutil.RequeueWithError\n\t/workspace/pkg/controllerutil/controller_common.go:31\ngithub.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisSentinelReconciler).Reconcile\n\t/workspace/controllers/redissentinel_controller.go:61\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-10-31T11:47:07Z","msg":"Reconciler error","controller":"redissentinel","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisSentinel","RedisSentinel":{"name":"redis-sentinel","namespace":"internal-develop-ci"},"namespace":"internal-develop-ci","name":"redis-sentinel","reconcileID":"a99ed7b7-7fc6-4167-8c8a-4d8736002640","error":"StatefulSet.apps \"redis-sentinel-sentinel\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
```

redis-operator version:
Helm chart: 0.18.2
Operator version:  0.18.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0-eks-a737599
</pre></details>

**What did you do?**

Upgrading redis-sentinel helm chart from  0.16.4 to 0.16.5

**What did you expect to see?**
STS from redis-sentinel updated with new image

**What did you see instead?**
The redis-operator error indicated above that it cannot update some sts field (I think it is the image, because it is the only change that helm diff shows):

```yaml
  # Source: redis-sentinel/templates/redis-sentinel.yaml
  apiVersion: redis.redis.opstreelabs.in/v1beta2
  kind: RedisSentinel
  metadata:
    name: redis-sentinel
    labels:
      app.kubernetes.io/name: redis-sentinel
-     helm.sh/chart: redis-sentinel-0.16.4
+     helm.sh/chart: redis-sentinel-0.16.5
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/instance: redis-sentinel
-     app.kubernetes.io/version: 0.16.4
+     app.kubernetes.io/version: 0.16.5
      app.kubernetes.io/component: middleware
      type: sentinel
  spec:
    clusterSize: 3
  # Sentinel Config 
    redisSentinelConfig:
      redisReplicationName: redis-replication
      masterGroupName : "mymaster"
      redisPort:  "6379"
      quorum: "2"
      parallelSyncs: "1"
      failoverTimeout: "180000"
      downAfterMilliseconds:  "30000"

    kubernetesConfig:
-     image: "quay.io/opstree/redis-sentinel:v7.0.12"
+     image: "quay.io/opstree/redis-sentinel:v7.0.15"
      imagePullPolicy: "IfNotPresent"
      resources: 
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    redisExporter:
      enabled: true
      image: "quay.io/opstree/redis-exporter:v1.44.0"
      imagePullPolicy: "IfNotPresent"
    podSecurityContext: 
      fsGroup: 1000
      runAsUser: 1000
    tolerations: 
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 5
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 5
internal-develop-ci, redis-sentinel-prometheus-monitoring, ServiceMonitor (monitoring.coreos.com) has changed:
  # Source: redis-sentinel/templates/servicemonitor.yaml
  apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: redis-sentinel-prometheus-monitoring
    labels:
      app.kubernetes.io/name: redis-sentinel
-     helm.sh/chart: redis-sentinel-0.16.4
+     helm.sh/chart: redis-sentinel-0.16.5
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/instance: redis-sentinel
-     app.kubernetes.io/version: 0.16.4
+     app.kubernetes.io/version: 0.16.5
      app.kubernetes.io/component: middleware
  spec:
    selector:
      matchLabels:
        app: redis-sentinel
        redis_setup_type: sentinel
        role: sentinel
    endpoints:
    - port: redis-exporter
      interval: 30s
      scrapeTimeout: 10s
    namespaceSelector:
      matchNames:
      - internal-develop-ci
```
