### ISSUE TITLE
Custom dnsConfig/dnsPolicy 

### ISSUE THREAD

**Issue by mahesh-kore** [OT-CONTAINER-KIT/redis-operator#1125]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version:
redis-operator-0.18.3

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
I attempted to add or update dnsConfig by modifying the RedisCluster CRD as shown below, but it didn't work. Are there any available workarounds
```
dnsConfig:
  nameservers:
    - 10.43.0.10
  options:
    # additional options here

```

**What did you expect to see?**

**What did you see instead?**
