### ISSUE TITLE
Bug: Error in redis-standalone.yaml for include function"

### ISSUE THREAD

**Issue by moeinshahcheraghi** [OT-CONTAINER-KIT/redis-operator#1145]
### Summary
There is an error in the Helm chart template `redis-standalone.yaml`. The `include` function is missing the required second argument, causing a rendering error.

### Steps to Reproduce
1. Use the Redis Helm chart with the following configuration:
```yaml
initContainer:
  enabled: true
  image: "busybox"
  imagePullPolicy: "IfNotPresent"
2. Run helm template or helm install.
3. Observe the following error:
```text
Error: template: redis/templates/redis-standalone.yaml:83:20: executing "redis/templates/redis-standalone.yaml" at <include>: wrong number of args for include: want 2 got 1
```
#Fix
Update the redis-standalone.yaml to correctly include the context in the include function:
```yaml
{{ include "initContainer.properties" . | nindent 4 }}
```
