### ISSUE TITLE
Initcontainer is not  working 

### ISSUE THREAD

**Issue by moeinshahcheraghi** [OT-CONTAINER-KIT/redis-operator#1147]
I attempted to configure an initContainer in the Redis Operator CRD to set vm.overcommit_memory=1 using the following configuration. However, the setting doesn't take effect, and Redis logs indicate warnings about improper memory overcommit configuration. This suggests the sysctl command was either not executed or didn't apply correctly.
```yml
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name:  redis-standalone
spec:
  kubernetesConfig:
    image: "quay.io/opstree/redis:v7.0.15"
    imagePullPolicy: "IfNotPresent"
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisExporter:
    enabled: true
    image: "quay.io/opstree/redis-exporter:v1.44.0"
    imagePullPolicy: "IfNotPresent"
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  storage: 
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: openebs-hostpath
  podSecurityContext: 
    fsGroup: 1000
    runAsUser: 1000

```
manifest is applied but init container is not working
I am describe the pod and the init container is not worked
