### ISSUE TITLE
webhook-server-cert secret not found

### ISSUE THREAD

**Issue by obitoquilt** [OT-CONTAINER-KIT/redis-operator#1162]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version: v0.18.1

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

1.27.4

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

I want to use webhook to convert cr from v1beta1 to v1beta2 version. 

values.yaml
```yaml
redisOperator:
  webhook: true
```

**What did you expect to see?**

The redis-operator will work

**What did you see instead?**

```
MountVolume.Setup failed for volume "cert": secret "webhook-server-cert" not found
```

I want to know how to create the `webhook-server-cert` secret.

**Comment by xiaozhuang-a** [comment]
please show you all operator values

**Comment by obitoquilt** [comment]
> please show you all operator values

Thanks for looking into this. 
```yaml
redisOperator:
  name: redis-operator
  webhook: true

certmanager:
  enabled: false
```

**Comment by norman-zon** [comment]
I am encountering the same problem. My values file:

```yaml
redisOperator:
  name: redis-operator
  webhook: true
issuer:
  create: false
  kind: ClusterIssuer
  name: letsencrypt
certificate:
  secretName: webhook-server-cert-letsencrypt
certmanager:
  enabled: true
  apiVersion: "cert-manager.io/v1"
```
