### ISSUE TITLE
how to print operator  log "logger.V(1).Info"

### ISSUE THREAD

**Issue by xiaozhuang-a** [OT-CONTAINER-KIT/redis-operator#1163]
**Describe your question**

**What version of redis-operator are you using?**

redis-operator version:

**Additional context**

**Comment by drivebyer** [comment]
try this

```
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --leader-elect
        - --zap-log-level  # new
        - "1"              # new
```
