### ISSUE TITLE
Data Loss After Restarting All Leaders and Followers in Redis Cluster

### ISSUE THREAD

**Issue by captainpro-eng** [OT-CONTAINER-KIT/redis-operator#1164]
We are currently running a Redis cluster with the following versions:
Redis Operator Helm Chart: 18.0.5
Redis Operator Image: 18.0.1
Redis Image: 7.0.12

We have tested multiple Redis failover scenarios, and in most cases, the cluster state is marked as "OK" and data is preserved after restarts. However, we encountered a scenario where restarting all the masters and slaves results in the cluster state being "OK", but all data is lost. Below is a summary of the test cases:

Tested Scenarios:

- Restarted 3 leaders only:  After all leaders came back up, the cluster state became "OK" and all data was preserved.

- Restarted all the leaders : After all leaders came back up, the cluster state became "OK" and all data was secure.

- Restarted all the followers : After all followers came back up, the cluster state became "OK" and all data was secure.

- Restarted 3 leaders and 3 followers : After all leaders and followers came back up, the cluster state became "OK" and all data was secure.

- Restarted all the leaders and all the followers: **After all masters and slaves came back up, the cluster state was "OK", but all data was lost.**

**Comment by captainpro-eng** [comment]
@drivebyer have u faced this?

**Comment by drivebyer** [comment]
> @drivebyer have u faced this?

No. Did you use RDB or AOF?

**Comment by captainpro-eng** [comment]
I’m using AOF.

**Comment by captainpro-eng** [comment]
@drivebyer have u check this?

**Comment by MuhammadQadora** [comment]
@drivebyer @captainpro-eng Hi, I am facing similar issue. I have set specStorage.KeepAfterDelete: true to persist the PVCs.
After a helm uninstall and reinstall, the data is lost. I can tell that the data is lost when the Sync happens between master and replica (before the state of the cluster changes to Ok).
I am using the latest version of both the operator and the RedisCluster

**Comment by captainpro-eng** [comment]
Can u share the redis cluster yaml?

**Comment by MuhammadQadora** [comment]
Sure thing!
```
---
redisCluster:
  name: "redis-cluster"
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  image: op-test
  tag: latest
  imagePullPolicy: IfNotPresent
  imagePullSecrets: {}
    # - name:  Secret with Registry credentials
  redisSecret:
    secretName: "redis-password"
    secretKey: "password"
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: 400m
      memory: 2Gi
  minReadySeconds: 0
  # -- Some fields of statefulset are immutable, such as volumeClaimTemplates.
  # When set to true, the operator will delete the statefulset and recreate it. Default is false.
  recreateStatefulSetOnUpdateInvalid: false
  leader:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: disktype
      #         operator: In
      #         values:
      #         - ssd
    tolerations: []
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"
    nodeSelector: null
      # memory: medium
    securityContext: {}
    pdb:
      enabled: false
      maxUnavailable: 1
      minAvailable: 1
    
  follower:
    replicas: 3
    serviceType: ClusterIP
    affinity: null
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: disktype
      #         operator: In
      #         values:
      #         - ssd
    tolerations: []
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"
    nodeSelector: null
      # memory: medium
    securityContext: {}
    pdb:
      enabled: false
      maxUnavailable: 1
      minAvailable: 1

labels: {}
#   foo: bar
#   test: echo


externalConfig:
  enabled: true
  data: |
    loadmodule /FalkorDB/bin/src/falkordb.so

externalService:
  enabled: false
  # annotations:
  #   foo: bar
  serviceType: LoadBalancer
  port: 6379

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
  # -- extraLabels are added to the servicemonitor when enabled set to true
  extraLabels: {}
    # foo: bar
    # team: devops

redisExporter:
  enabled: false
  image: quay.io/opstree/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  env: []
    # - name: VAR_NAME
    #   value: "value1"

sidecars:
  name: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  env: {}
    # - name: MY_ENV_VAR
    #   value: "my-env-var-value"

initContainer:
  enabled: false
  image: ""
  imagePullPolicy: "IfNotPresent"
  resources: {}
    # requests:
    #   memory: "64Mi"
    #   cpu: "250m"
    # limits:
    #   memory: "128Mi"
    #   cpu: "500m"
  env: []
  command: []
  args: []

priorityClassName: ""

storageSpec:
  keepAfterDelete: true
  volumeClaimTemplate:
    spec:
      # storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  nodeConfVolume: true
  nodeConfVolumeClaimTemplate:
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  #   selector: {}

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000


# serviceAccountName: redis-sa

TLS:
  ca: ca.crt
  cert: tls.crt
  key: tls.key
  secret:
    secretName: ""

acl:
  secret:
    secretName: ""

env: []
  # - name: VAR_NAME
  #   value: "value1"

serviceAccountName: ""

```
