### ISSUE TITLE
[redis-replication] On create podSecurityContext  is removed from RedisReplication object (then in Statelfulset)

### ISSUE THREAD

**Issue by sogos** [OT-CONTAINER-KIT/redis-operator#1185]
redis-operator chart: 0.18.5
redis-operator version: 0.18.1

**Does this issue reproduce with the latest release?**

``````
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisReplication
metadata:
  name: redis-replication
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis-replication
spec:
  priorityClassName: opencti-core-components
  clusterSize: 2
  redisConfig:
    additionalRedisConfig: redis-external-config
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
[...]
``````````````````

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.29.11
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1

</pre></details>

**What did you do?**

`kubectl apply -f my-redis-replication.yml`

**What did you expect to see?**

The podSecurityContext is persisted, the statefulset contain also the portion of configuration

**What did you see instead?**

The podSecurityContext is erased and i have to patch the RedisReplication object to have the param

`kubectl patch redisreplication redis-replication -n XXX --type=merge -p '{"spec":{"podSecurityContext":{"runAsUser":1000,"fsGroup":1000}}}'`
