### ISSUE TITLE
Ability to add labels to ServiceMonitor via the value file

### ISSUE THREAD

**Issue by AharonIsraelCohen** [OT-CONTAINER-KIT/redis-operator#1187]
I am using redis-cluster chart version: 0.16.4
And I need to add some extra labels to the serviceMonitor of the leaders and followers for prometheus.
currently I added it directly on the templates/leader-sm.yaml and templates/follower-sm.yaml files
would be very nice to have the ability to have costume labels via the value file

something like:

```
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
  labels:
    foo: bar
```
