### ISSUE TITLE
Add support for custom annotations on headless svc in Redis CRD and Redis/Redis-Cluster helm charts

### ISSUE THREAD

**Issue by georgelazaroff** [OT-CONTAINER-KIT/redis-operator#1212]
**Is your feature request related to a problem? Please describe.**
The current Redis and Redis-Cluster CRD and Helm charts provided by OT-CONTAINER-KIT do not allow users to add custom annotations to headless services. This limitation makes it challenging to integrate with tools like external-dns or other systems that require specific annotations on services for automation and configuration.

**Describe the solution you'd like**
I would like the CRD for Redis and Redis-Cluster, as well as the Helm charts, to include support for specifying custom annotations on the headless services. This could be implemented as an optional field in the CRD and values.yaml file, allowing users to define custom annotations.

**Describe alternatives you've considered**
I have created a separate headless service with custom annotations as shown below:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${redis_main_domain}.
    external-dns.alpha.kubernetes.io/ttl: "30"
  labels:
    app: ${redis_name}
  name: ${redis_name}-headless-external
  namespace: ${redis_namespace}
spec:
  clusterIP: None
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: ${redis_name}
  type: ClusterIP
```

**What version of redis-operator are you using?**

redis-operator version: 0.19.1
Redis CRD and redis helm chart version: 0.16.5

**Additional context**
Adding support for custom annotations on headless services would make the Redis and Redis-Cluster charts more flexible and easier to integrate into various environments. This feature would particularly benefit users leveraging Kubernetes-native DNS management tools like external-dns
