### ISSUE TITLE
Failed to override "upstream-opm-builder" and "quay.io/operatorhubio/redis-operator:v0.6.0" from private registry

### ISSUE THREAD

**Issue by soleimaniamir** [OT-CONTAINER-KIT/redis-operator#125]
Hello
I'm trying to run Redis-cluster into my Kubernetes cluster, after replacing all Docker images in YAML files, I deployed `Subscription` into the cluster with this deploy file:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-redis-operator
  namespace: operators
spec:
  channel: stable
  name: redis-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
```

but there is a workload in the `olm` namespace with `quay.io/operatorhubio/redis-operator:v0.6.0` and `quay.io/operator-framework/upstream-opm-builder:latest` images and I don't know how I should replace them with images located in my private registry.
I'm using CRDs to deploy Redis-cluster into my Kubernetes cluster.
