### ISSUE TITLE
Redis cluster pods is CrashLoopBackOff again and again

### ISSUE THREAD

**Issue by xls56iii** [OT-CONTAINER-KIT/redis-operator#1253]
**What version of redis operator are you using?**

redis-operator version: `v0.19.1`

**Does this issue reproduce with the latest release?**
**Yes**

**What operating system and processor architecture are you using (`kubectl version`)?**

Client Version: `v1.30.2`
Kustomize Version: `v5.0.4-0.20230601165947-6ce0bf390ce3`
Server Version: `v1.30.5`

**What did you do?**
This is my CR, 
```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 5
  redisFollower:
    replicas: 5
  clusterVersion: v7
  persistenceEnabled: false
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    redisSecret:
      name: redis-secret
      key: password
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    nodeConfVolume: true
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```
I just use:
1. `kubectl apply -f redis-cr.yml -n k8s-redis`, with the `clusterSize:5`, `redisFollower.replicas:5`
2.  scale in to `clusterSize:3`, `redisFollower.replicas:3`
3. `kubectl apply -f redis-cr.yml -n k8s-redis`

**What did you expect to see?**
All pods should be running. And cluster should be okay.

**What did you see instead?**
Sometimes it's okay, but it doesn't last very long. I also checked the `cluster nodes`, the ip all are right.

![Image](https://github.com/user-attachments/assets/bb1ea8d1-7bda-4a4b-89ad-eefc4915c763)

I can see these logs in redis-cluster-leader-1
```
19:S 28 Feb 2025 03:09:33.679 * MASTER <-> REPLICA sync: Flushing old data
19:S 28 Feb 2025 03:09:33.679 * MASTER <-> REPLICA sync: Loading DB in memory
19:S 28 Feb 2025 03:09:33.683 * Loading RDB produced by version 7.0.12
19:S 28 Feb 2025 03:09:33.683 * RDB age 0 seconds
19:S 28 Feb 2025 03:09:33.683 * RDB memory usage when created 1.72 Mb
19:S 28 Feb 2025 03:09:33.683 * Done loading RDB, keys loaded: 0, keys expired: 0.
19:S 28 Feb 2025 03:09:33.684 * MASTER <-> REPLICA sync: Finished with success
19:S 28 Feb 2025 03:09:34.033 # Cluster state changed: fail
19:S 28 Feb 2025 03:09:55.808 * Marking node 937c789b54e874d07fb9288651620792ec53df7f as failing (quorum reached).
19:S 28 Feb 2025 03:09:55.999 * Clear FAIL state for node 15739057fcd848b51b83e58f32c26a308883214b: is reachable again and nobody is serving its slots after some time.
19:S 28 Feb 2025 03:09:56.198 # Cluster state changed: ok
19:S 28 Feb 2025 03:09:56.801 * Marking node cbc073488f4778b6e61ea7acc5c13fe74b5e1ded as failing (quorum reached).
Stream closed EOF for k8s-redis/redis-cluster-leader-1 (redis-cluster-leader)
```
