### ISSUE TITLE
How to expose the redis leader not the follower?

### ISSUE THREAD

**Issue by gadonski** [OT-CONTAINER-KIT/redis-operator#1273]
**Describe your question**
i´ve ben try to expose the redis outside the cluster, but always expose the follower not the leader. How can i change it?

![Image](https://github.com/user-attachments/assets/04e1e888-0c58-435a-887f-9092c7423a99)

**What version of redis-operator are you using?**

redis-operator version: v7.0.15

**Additional context**
The external service was exposed by these config:

```
externalService:
  enabled: true
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.70.31.103
  serviceType: LoadBalancer
  port: 6379
```
