### ISSUE TITLE
document `redisReplicationPassword` re: Sentinel setup

### ISSUE THREAD

**Issue by garyburgmann** [OT-CONTAINER-KIT/redis-operator#1318]
**Which document needs to be updated?**
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/5ea1410f20b31b0711b154fa1d40c0d42f610d23/config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml#L2552

```yaml
redisSentinelConfig:
    ...
    redisReplicationPassword:
                    description: EnvVarSource represents a source for the value of
                      an EnvVar.
                    properties:
                      configMapKeyRef:
                        description: Selects a key of a ConfigMap.
                        properties:
                          key:
                            description: The key to select.
                            type: string
                          name:
                            description: |-
                              Name of the referent.
                              More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                              TODO: Add other useful fields. apiVersion, kind, uid?
                            type: string
                          optional:
                            description: Specify whether the ConfigMap or its key
                              must be defined
                            type: boolean
                        required:
                        - key
                        type: object
                        x-kubernetes-map-type: atomic
                      fieldRef:
                        description: |-
                          Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`,
                          spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
                        properties:
                          apiVersion:
                            description: Version of the schema the FieldPath is written
                              in terms of, defaults to "v1".
                            type: string
                          fieldPath:
                            description: Path of the field to select in the specified
                              API version.
                            type: string
                        required:
                        - fieldPath
                        type: object
                        x-kubernetes-map-type: atomic
                      resourceFieldRef:
                        description: |-
                          Selects a resource of the container: only resources limits and requests
                          (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
                        properties:
                          containerName:
                            description: 'Container name: required for volumes, optional
                              for env vars'
                            type: string
                          divisor:
                            anyOf:
                            - type: integer
                            - type: string
                            description: Specifies the output format of the exposed
                              resources, defaults to "1"
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          resource:
                            description: 'Required: resource to select'
                            type: string
                        required:
                        - resource
                        type: object
                        x-kubernetes-map-type: atomic
                      secretKeyRef:
                        description: Selects a key of a secret in the pod's namespace
                        properties:
                          key:
                            description: The key of the secret to select from.  Must
                              be a valid secret key.
                            type: string
                          name:
                            description: |-
                              Name of the referent.
                              More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                              TODO: Add other useful fields. apiVersion, kind, uid?
                            type: string
                          optional:
                            description: Specify whether the Secret or its key must
                              be defined
                            type: boolean
                        required:
                        - key
                        type: object
                        x-kubernetes-map-type: atomic
                    type: object
    ...
```

**Expected changes**
Will create PR to include a manifest with RedisReplication and RedisSentinel declared using password from a Secret

**What version of redis-operator are you using?**

redis-operator version: 0.19.3

**Additional context**
-
