### ISSUE TITLE
Docs: `spec.securityContext` should be `spec.podSecurityContext` in Cluster YAML Manifest Example

### ISSUE THREAD

**Issue by liboshuai01** [OT-CONTAINER-KIT/redis-operator#1345]
**Which document needs to be updated?**
The documentation page for Redis Cluster setup, specifically under the 'YAML Installation' section.
The path is: `Installation > Getting Started > Cluster`.

The error is in the sample manifest provided for deploying a Redis cluster using YAML:
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  clusterVersion: v7
  securityContext: # <--- This field is incorrect
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: Always
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```

**Expected changes**
The `spec.securityContext` field in the sample RedisCluster YAML manifest should be changed to `spec.podSecurityContext`.

The corrected section of the manifest should look like this:
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  clusterVersion: v7
  podSecurityContext: # <--- Corrected field name
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: Always
  # ... rest of the manifest
```

**What version of redis-operator are you using?**
The documentation example uses `apiVersion: redis.redis.opstreelabs.in/v1beta2` for the `RedisCluster` kind. The error occurs when trying to apply this manifest, suggesting the issue is with the CRD definition for this version (or a newer one that maintains this structure).

**Additional context**
When attempting to apply the `cluster.yaml` manifest as provided in the documentation, `kubectl apply` fails with the following error:

```
[root@master operator]# kubectl apply -f cluster.yaml
Error from server (BadRequest): error when creating "redis-cluster/clusterd.yaml": RedisCluster in version "v1beta2" cannot be handled as a RedisCluster: strict decoding error: unknown field "spec.securityContext"
```
This error message clearly indicates that `spec.securityContext` is not a valid field at that location for the `RedisCluster` v1beta2 Kind. The correct field, as per common Kubernetes practices for pod-level security contexts within custom resources, is typically `spec.podSecurityContext`.

I am willing to submit a Pull Request to correct this in the documentation.
