### ISSUE TITLE
Bug: unable to specify SecurityContext for `RedisCluster` in API `v1beta2`

### ISSUE THREAD

**Issue by DodoLeDev** [OT-CONTAINER-KIT/redis-operator#1352]
**What version of redis operator are you using?**

redis-operator version: `quay.io/opstree/redis-operator:v0.15.1`, as provided by OLM, but the bug [still persists in v0.20.2](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.20.2/api/v1beta2/rediscluster_types.go#L40)

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>

## Kubernetes
Client Version: v1.29.14
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0

### Minikube
Version: v1.34.0
commit: 210b148df93a80eb872ecbeb7e35281b3c582c61

</pre></details>

**What did you do?**

I tried to deploy a RedisCluster with this configuration:
```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
...
```

**What did you expect to see?**

The operator should allow the deployment of my resource, as it does for a [`Redis`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.20.2/api/v1beta2/redis_types.go#L35), [`RedisReplication`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.20.2/api/v1beta2/redisreplication_types.go#L17) or [`RedisSentinel`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.20.2/api/v1beta2/redissentinel_types.go#L18) resource

**What did you see instead?**
The operator don't want me to be happy with Redis Clusters

**Why is it important?**

This securityContext is needed to pass the Enforced "Restricted" Kubernetes Security Standard
