### ISSUE TITLE
v0.20.2 Fails Readiness / Liveness probe

### ISSUE THREAD

**Issue by Belly-Buster** [OT-CONTAINER-KIT/redis-operator#1353]
**What version of redis operator are you using?**

v0.20.2

**What operating system and processor architecture are you using (`kubectl version`)?**

$ kubectl version

Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.3+k3s1

**What did you do?**

helm install redis-operator ot-helm/redis-operator --version 0.20.2

**What did you expect to see?**

The cluster operator start

**What did you see instead?**

Readiness probe errored: strconv.Atoi: parsing "probe": invalid syntax
Liveness probe errored: strconv.Atoi: parsing "probe": invalid syntax

pods do not start

**Comment by dimpavloff** [comment]
+1, am just observing the same

**Comment by Belly-Buster** [comment]
Likely https://github.com/OT-CONTAINER-KIT/redis-operator/commit/b39b901c1b2db18793f710b44c351f7289d6f0c7

**Comment by ctrmcubed** [comment]
Webhook conditional needs to be down to ensure the probe port is always present. Will do a PR later.

```
        ports:
        - containerPort: 8081
          name: probe
          protocol: TCP
      {{- if .Values.redisOperator.webhook }}
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      {{- end }}
```
