### ISSUE TITLE
redisOperator issue with probes configuration

### ISSUE THREAD

**Issue by MoZadro** [OT-CONTAINER-KIT/redis-operator#1390]
**What version of redis operator are you using?**
v0.20.2

```shell
kubectl describe pod 

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  88s                default-scheduler  Successfully assigned redis-operator/redis-operator-7958b5f467-45rlh to p-k8srke-srv-c01n01
  Normal   Pulling    74s                kubelet            Pulling image "ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.20.2"
  Normal   Pulled     73s                kubelet            Successfully pulled image "ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.20.2" in 679ms (679ms including waiting). Image size: 14865101 bytes.
  Normal   Created    73s                kubelet            Created container redis-operator
  Normal   Started    73s                kubelet            Started container redis-operator
  Warning  Unhealthy  9s (x10 over 72s)  kubelet            Readiness probe errored: strconv.Atoi: parsing "probe": invalid syntax
  Warning  Unhealthy  9s (x7 over 69s)   kubelet            Liveness probe errored: strconv.Atoi: parsing "probe": invalid syntax

```

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**
v1.33.0

**What did you do?**
I tried to update redisOperator version to version 0.20.2

**What did you expect to see?**
I expect the Redis Operator pods to start successfully, but due to a misconfiguration with the probes, they fail to do so.

**What did you see instead?**
It appears that Redis Operator version 0.20.2 has a misconfiguration in its liveness and readiness probes. Specifically, the probes are defined with port: probe, which is not a valid port specification. This leads to the error strconv.Atoi: parsing "probe": invalid syntax, indicating that the system is attempting to parse the string "probe" as an integer, which fails.

In the deployment configuration, the liveness and readiness probes are specified as follows:

```
livenessProbe:
    failureThreshold: 3
    httpGet:
         path: /healthz
         port: probe
         scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
name: redis-operator
readinessProbe:
     failureThreshold: 3
      httpGet:
          path: /readyz
          port: probe
          scheme: HTTP
       periodSeconds: 10
       successThreshold: 1
       timeoutSeconds: 1
```

The container must define a port with the name "probe". If such a named port is not defined, Kubernetes cannot resolve "probe" to an actual port number, resulting in error.
