### ISSUE TITLE
Invalid Standalone default config

### ISSUE THREAD

**Issue by davidpechcz** [OT-CONTAINER-KIT/redis-operator#1399]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```
not relevant

redis-operator version: 0.20.2+ (current main)

**Does this issue reproduce with the latest release?**
yes

**What did you do?**

Deploy the example:

```
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: standalone
  namespace: expriment-redis-opstree
spec:
  kubernetesConfig:
```

Does not work because of failing readiness probe:
```
  containerStatuses:
...
    name: standalone
    ready: false
    restartCount: 335
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=standalone pod=standalone-0_expriment-redis-opstree(5e3b3043-fa69-4b34-b0a8-8be286c8277e)
        reason: CrashLoopBackOff
```
Reason
```
│   Warning  Unhealthy  23m (x1773 over 16h)    kubelet  Readiness probe failed: Could not connect to Redis at standalone-0:6379: Connection refused                           │
```
Problem is default env config:
```
spec:
  containers:
  - env:
    - name: REDIS_ADDR
      value: redis://localhost:6379
```

**What did you expect to see?**

I expect examples to work.

**What did you see instead?**

Crash-loop.
