### ISSUE TITLE
RedisSentinel not picked up by operator, no error visible

### ISSUE THREAD

**Issue by davidpechcz** [OT-CONTAINER-KIT/redis-operator#1401]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

```
{"level":"info","ts":"2025-06-09T13:51:10Z","logger":"setup","msg":"starting manager"}
{"level":"info","ts":"2025-06-09T13:51:10Z","logger":"controller-runtime.metrics","msg":"Starting metrics server"}
{"level":"info","ts":"2025-06-09T13:51:10Z","msg":"starting server","kind":"health probe","addr":"[::]:8081"}
{"level":"info","ts":"2025-06-09T13:51:10Z","logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":8080","secure":false}
I0609 13:51:10.915011       1 leaderelection.go:250] attempting to acquire leader lease expriment-redis-opstree/6cab913b.redis.opstreelabs.in...
I0609 13:51:27.232312       1 leaderelection.go:260] successfully acquired lease expriment-redis-opstree/6cab913b.redis.opstreelabs.in
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"redis","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"Redis","source":"kind source: *v1beta2.Redis"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting Controller","controller":"redis","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"Redis"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"redisreplication","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisReplication","source":"kind source: *v1beta2.RedisReplication"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"redisreplication","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisReplication","source":"kind source: *v1.StatefulSet"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting Controller","controller":"redisreplication","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisReplication"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"redissentinel","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisSentinel","source":"kind source: *v1beta2.RedisSentinel"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"redissentinel","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisSentinel","source":"kind source: *v1beta2.RedisReplication"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting Controller","controller":"redissentinel","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisSentinel"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"rediscluster","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisCluster","source":"kind source: *v1beta2.RedisCluster"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting EventSource","controller":"rediscluster","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisCluster","source":"kind source: *v1.StatefulSet"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting Controller","controller":"rediscluster","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisCluster"}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting workers","controller":"redis","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"Redis","worker count":1}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting workers","controller":"redissentinel","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisSentinel","worker count":1}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting workers","controller":"redisreplication","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisReplication","worker count":1}
{"level":"info","ts":"2025-06-09T13:51:27Z","msg":"Starting workers","controller":"rediscluster","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisCluster","worker count":1}
{"level":"info","ts":"2025-06-10T06:54:13Z","logger":"KubeAPIWarningLogger","msg":"metadata.finalizers: \"redisSentinelFinalizer\": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers"}
{"level":"info","ts":"2025-06-10T06:54:13Z","logger":"KubeAPIWarningLogger","msg":"metadata.finalizers: \"redisFinalizer\": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers"}
```

redis-operator version: 0.20.2

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.7-gke.1390000", GitCommit:"d83cb9ce90bb38abf245cdfd7145e5a7a10e6006", GitTreeState:"clean", BuildDate:"2025-04-21T04:17:04Z", GoVersion:"go1.23.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

Deployed operator via Helm chart, deployed this CRD:
```
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: sentinel
  namespace: expriment-redis-opstree
spec:
  clusterSize: 2
  redisSentinelConfig: 
    redisReplicationName : redis-replication
  kubernetesConfig:
    image: PRIVATE_REPO/redis-sentinel:v7.0.15
    imagePullSecrets:
      - name: docker-pull
 ```

**What did you expect to see?**

Working redis installation

**What did you see instead?**

Nothing - I can just that the operator has some extra lines, so it must have seen the crds, but no error anywhere is visible.

**Comment by bygzyz** [comment]
i got the same issue

**Comment by hapeho** [comment]
detto

**Comment by nrlpenneo** [comment]
Same

**Comment by hanqish** [comment]
Same

**Comment by drivebyer** [comment]
Your RedisSentinel is waiting for the RedisReplication resource to be ready. The controller requires a RedisReplication named redis-replication (as specified in your redisReplicationName) to exist and be fully operational before it will configure the Sentinel.

Try to create an relication cluster like:
```yaml
  apiVersion: redis.redis.opstreelabs.in/v1beta2
  kind: RedisReplication
  metadata:
    name: redis-replication  # Must match your redisReplicationName
    namespace: expriment-redis-opstree
  spec:
    clusterSize: 3
    kubernetesConfig:
      image: PRIVATE_REPO/redis:v7.0.15
      imagePullSecrets:
      - name: docker-pull
```
