### ISSUE TITLE
Unable to get redis cluster running with TLS support

### ISSUE THREAD

**Issue by croessner** [OT-CONTAINER-KIT/redis-operator#1410]
**What version of redis operator are you using?**

helm list:
```
redis-operator           	ot-operators     	1       	2025-06-17 15:59:01.973868 +0200 CEST	deployed	redis-operator-0.20.3          	0.20.2
```

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

```
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.4
```

**What did you do?**

1. Install the operator.

I changed the webhook to "true" and enabled the cert_manager. This creates a new secret

2. Try installing the cluster

I want pod anti-affinity, so I enabled this flag. At the bottom under TLS, I entered a ca.crt, tls,crt and tls.key. I had created it before like this:

```yaml
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-selfsigned-issuer
  namespace: ot-operators
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-cluster-cert
  namespace: ot-operators
spec:
  secretName: redis-tls
  duration: 2160h # 90 Tage
  renewBefore: 360h # 15 Tage
  subject:
    organizations:
      - redis
  commonName: redis-cluster
  dnsNames:
    - redis-cluster
    - redis-cluster.ot-operators
    - redis-cluster.ot-operators.svc
  issuerRef:
    name: redis-selfsigned-issuer
    kind: Issuer
  privateKey:
    algorithm: RSA
    size: 2048
````

**What did you expect to see?**

I was hoping to see a cluster, were 1.) master and slave are not running on the same node and 2.) all cluster nodes have TLS enabled.

**What did you see instead?**

I can see that the cert, key and ca were successfully created. The operator tells me that it found an bad certificate and it fails to init the cluster. No pods get created.

If I disable the webhook and cert_manager in the operator, the cluster gets created, but then Redis tells me that it has invalid certificates.

Currently I only get it running without TLS and master/slave are on the same nodes (3 worker nodes)

> Note
>
> I would hope there would exist a little bit more documentation here to clarify things. I do not understand the "webhook" usage. What is it, why does it require TLS? What does it have to do with the anti-affinity stuff, etc. :-)
