### ISSUE TITLE
Is is possible to Create a Redis Cluster with 2 Replicas

### ISSUE THREAD

**Issue by d80tb7** [OT-CONTAINER-KIT/redis-operator#185]
Hello,

I was trying to use the operator to have 2 followers per leader, i.e. a replication factor of 2, but couldn't find a way to achieve this.  Is this possible with the operator?

many thanks,

Chris

**Comment by davidcollom** [comment]
I don't think this is possible within the current structure, do you have any thoughts on an API in terms of how your resource would look?

Something that comes to mind for myself was something like:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  redisLeader:
    size: 1
  redisFollower:
    replicationFactor: 2
```

Resulting in 1 Leader and 2 Followers, Increasing Leaders to 3 (for N+1) would result in 6 Leaders, where Leader%Follower would be used to determine the Leader in which the Follower would replicate from?

**Comment by apena-matriz** [comment]
I think just specifying the number of followers **replicationFactor** would be enough and keep using **clusterSize** to deploy the desired amount of leaders. Maybe something like this:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3 # Desired amount of leaders
  redisFollower:
    replicationFactor: 2 # Followers per leader
```

Could this be posible ?

Thanks
