### ISSUE TITLE
Cluster installation does not work with Istio ingress gateway

### ISSUE THREAD

**Issue by kvendingoldo** [OT-CONTAINER-KIT/redis-operator#235]
Hello,
I'm trying to expose Redis via Istio ingress gateway

```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: redis-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 6379
        name: redis
        protocol: REDIS
      hosts:
        - "*"
```

```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redis-order
spec:
  hosts:
    - "<MY_DNS_NAME>"
  gateways:
    - redis/redis-gateway
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: redis-order-cluster-leader
            port:
              number: 6379
```

From istio ingress gateway I've configured port:
```
              - port: 6379
                targetPort: 6379
                name: redis
                protocol: TCP
```

and enabled filter on istiod via `PILOT_ENABLE_REDIS_FILTER` env variable.

When I'm trying to do any performance testing I'm getting the following error:
```
redis-benchmark -h <MY_DNS_NAME> -p 6379 -t get,set                                                
ERROR: unsupported command 'CONFIG'
ERROR: failed to fetch CONFIG from <MY_DNS_NAME>:6379
WARN: could not fetch server CONFIG
Error from server: MOVED 13782 10.160.2.41:6379ll: nan)
```

From network side port 6379 opened. Do you have any idea how to fix it?
