### ISSUE TITLE
typo doubt in example/external_service/cluster-svc.yaml

### ISSUE THREAD

**Issue by zmrdltl** [OT-CONTAINER-KIT/redis-operator#263]
**Is your feature request related to a problem? Please describe.**
I'm testing external_service with these files from example/external_service directory. 

cluster-svc.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster-leader
    redis_setup_type: cluster
    role: leader
  name: redis-cluster-leaders
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cluster-leader
    redis_setup_type: cluster
    role: leader
# type: LoadBalancer
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster-follower
    redis_setup_type: cluster
    role: follower
  name: redis-cluster-follower
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cluster-follower
    redis_setup_type: cluster
    role: follower
# type: LoadBalancer
  type: NodePort
```
This is the output statement after applying the following file in the k8s environment and `kubectl get svc`.
<br/>
![svc-nodeport](https://user-images.githubusercontent.com/22141521/161478668-18484332-e108-4d1a-af3b-b2b48c7f4abc.png)
Two NodePort type service named `redis-cluster-follower` and NodePort type service named `redis-cluster-leaders` are created.

Then i applied `cluster.yaml` file
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```
Then i printed svc. Since the services with the `redis-cluster-follower` name overlap, we confirmed that the service type is changed from `nodeport` to `clusterip` as follows.
<br/>
![image](https://user-images.githubusercontent.com/22141521/161479040-aeb0e97e-ceac-4f9a-b7fb-ba78113de616.png)

**Describe alternatives you've considered**

If redis-cluster-follower, the service name defined in cluster-svc.yaml, is a typo, I want to change it to redis-cluster-followers.

**What version of redis-operator are you using?**

redis-operator version: v0.10.0

**Additional context**

If it's not a typo, I wonder why it was designed this way.
