### ISSUE TITLE
unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.Redis.spec.kubernetesConfig

### ISSUE THREAD

**Issue by pandeybk** [OT-CONTAINER-KIT/redis-operator#267]
When trying to deploy standalone operator as mentioned in doc as follows,

```
# Create redis standalone setup
$ helm upgrade redis ot-helm/redis \
  --install --namespace goglides-platform
```

I am seeing following issue,

Error log,
```
error validating data: ValidationError(Redis.spec.kubernetesConfig): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.Redis.spec.kubernetesConfig
```

Helm chart version for standalone operator 
```
apiVersion: v1
appVersion: 0.10.0
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
home: https://github.com/ot-container-kit/redis-operator
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
- redis-exporter
maintainers:
- name: Opstree Solutions
name: redis
sources:
- https://github.com/ot-container-kit/redis-operator
version: 0.10.0
```

Snippets of helm config (all configuration used are default value mentioned in helm chart, nothing changed)

```
redisStandalone:
  image: quay.io/opstree/redis
  tag: v6.2.5
  imagePullPolicy: IfNotPresent
  # redisSecret:
  #   secretName: redis-secret
  #   secretKey: password
  serviceType: ClusterIP
  resources: {}
```
