### ISSUE TITLE
Redis Cluster - fail clustering

### ISSUE THREAD

**Issue by zmrdltl** [OT-CONTAINER-KIT/redis-operator#268]
**What version of redis operator are you using?**
v0.10.0
```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

**What operating system and processor architecture are you using (`kubectl version`)?**
v1.22.2
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
redis-secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
data:
  password: YmFyCg== #encoded by base64 origin value : bar 
```

redis-cluster.yaml
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    redisSecret:
      name: redis-secret
      key: password
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: csi-cephfs-sc
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

```

pod status
```shell
$ kubectl get pods -n mskim
NAME                            READY   STATUS    RESTARTS   AGE
redis-cluster-follower-0        1/1     Running   0          46m
redis-cluster-follower-1        1/1     Running   0          46m
redis-cluster-follower-2        1/1     Running   0          45m
redis-cluster-leader-0          1/1     Running   0          46m
redis-cluster-leader-1          1/1     Running   0          46m
redis-cluster-leader-2          1/1     Running   0          45m
```
```
redis-cli container in redis-cluster-leader-0 pod
$ kubectl -n mskim exec -it redis-cluster-leader-0 -- bash
bash-4.4# redis-cli
127.0.0.1:6379> keys *
(error) NOAUTH Authentication required.
127.0.0.1:6379> auth bar
OK
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> cluster info
cluster_state:fail
cluster_slots_assigned:0
cluster_slots_ok:0
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:0
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
127.0.0.1:6379> exit

bash-4.4# cat nodes.conf 
c80728ca3e907c88eca42c3a1b5d4cb9ba297ef9 :0@0 myself,master - 0 0 0 connected
vars currentEpoch 0 lastVoteEpoch 0
```

redis operator log
```text
2022-04-20T05:53:19.702Z        INFO    controller_redis        Successfully executed the command       {"Request.RedisManager.Namespace": "mskim", "Request.RedisManager.Name": "redis-cluster", "Command": ["redis-cli", "--cluster", "create", "10.244.29.204:6379", "10.244.136.220:6379", "10.244.136.248:6379", "--cluster-yes", "-a", "bar\n"], "Output": "\u001b[31;1mNode 10.244.29.204:6379 replied with error:\nWRONGPASS invalid username-password pair or user is disabled.\n\u001b[0m"}
2022-04-20T05:53:19.702Z        INFO    controllers.RedisCluster        Will reconcile redis cluster operator in again 10 seconds       {"Request.Namespace": "mskim", "Request.Name": "redis-cluster"}
```
