### ISSUE TITLE
Specifying the field `redisFollower.pdb` does not have any effect

### ISSUE THREAD

**Issue by hoyhbx** [OT-CONTAINER-KIT/redis-operator#287]
**What version of redis operator are you using?**

redis-operator version: We are using redis-operator built from the `HEAD`
- https://github.com/OT-CONTAINER-KIT/redis-operator/commit/f1c547e26ece015c0c5cd8a8549ff277e8e7c2ab

**Does this issue reproduce with the latest release?**

Yes, it reproduces with `quay.io/opstree/redis-operator:v0.10.0`

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-19T19:53:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I tried to create a `PodDisruptionBudget` resource for followers only. To do this, I applied the below YAML file
but no PodDisruptionBudget was created.

This bug causes the field `redisFollower.pdb` to be `no-op`, which causes unexpected reduced reliability of the application.

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisFollower:
    pdb:
      enabled: true
      minAvailable: 2
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

**What did you expect to see?**

I expect to see a `PodDisruptionBudget` being created for followers.

**What did you see instead?**

No `PodDisruptionBudget` resources were created, which is known by looking at the operator log and using `kubectl get poddisruption budget -A`.

**Possible root cause and fix**

Looking at the Reconciler function, `ReconcileRedisPodDisruptionBudget` is called for both leader and follower. https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/controllers/rediscluster_controller.go#L79-L95. 

However, inside `ReconcileRedisPodDisruptionBudget`, only information under `redisLeader.pdb` is used as can be seen from https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/poddisruption.go#L20-L24.

The function leaves `redisFollower.pdb` ineffective, and as long as `redisLeader.pdb` is specified, `PodDisruptionBudget` will be created for both leader and follower.

We think if it is an intended behavior that leader and follower should always have the same `PodDisruptionBudget`, `pdb` should not be a per-role field but an cluster setting. On the contrary, if this is not the intended behavior, the function `ReconcileRedisPodDisruption` should be fixed.
