### ISSUE TITLE
Is there support for replication without sharding?

### ISSUE THREAD

**Issue by doronl** [OT-CONTAINER-KIT/redis-operator#295]
When I try the below I get:

RedisCluster.redis.redis.opstreelabs.in "redis-primary" is invalid: spec.redisLeader.replicas: Invalid value: 1: spec.redisLeader.replicas in body should be greater than or equal to 3

```

redisCluster:
  clusterSize: 3
  image: quay.io/opstree/redis
  tag: v5.0.0
  imagePullPolicy: IfNotPresent
  leader:
    replicas: 1
    serviceType: ClusterIP
    affinity: {}
  follower:
    replicas: 2
```

I need an HA cluster spread across 3 AZs (I don't need sharding...), just high availability, can this be achieved with this operator?
