### ISSUE TITLE
Applications keep crashing when probe settings are incorrect

### ISSUE THREAD

**Issue by hoyhbx** [OT-CONTAINER-KIT/redis-operator#297]
**What version of redis operator are you using?**

redis-operator version: We are using redis-operator built from the `HEAD`
- https://github.com/OT-CONTAINER-KIT/redis-operator/commit/f1c547e26ece015c0c5cd8a8549ff277e8e7c2ab

**Does this issue reproduce with the latest release?**
Yes, the problem reproduces with `quay.io/opstree/redis-operator:v0.10.0`

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-19T19:53:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
I tried to create a redis-cluster with tcpSocket as the liveness probe handler with the below cr input. However, the created pod keeps crashing.

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisLeader:
    livenessProbe:
      tcpSocket:
        port: 8500 
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

Note that the field `redisLeader.livenessProbe` is different from the default value `usr/bin/healthcheck.sh` as the handler for livenessProbe and readinessProbe as revealed in https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/statefulset.go#L361-L364. It may be unsupported by the redis image.

**What did you expect to see?**
With the submitted CR, I am expecting:
1. If the input is valid and supported, the operator successfully sets the new readinessProbe setting and the redis pods do not crash.
2. If the input is invalid or not supported, the operator rejects the invalid input and returns an error.

1. The input does not pass operator's validation and is rejected.
5. The operator detects the unhealthy status of pods when executing `getRedisServerIP`. It should print out logs like "[`Error in getting redis pod IP`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/redis.go#L33)". From this point, the operator could either
    1. stop doing anything until the user submits a new valid input.
    2. try to fix the incorrect probing settings.

**What did you see instead?**
The operator's behavior does not conform to any one of the two behaviors described above.
If the readinessProbe is not supported by the application image, the operator should reject it and return an error message.

My application crashed and remained in a completely unavailable way.
```
default              pod/test-cluster-leader-0                        0/1     CrashLoopBackOff   6 (54s ago)   9m29s
default              pod/test-cluster-leader-1                        0/1     CrashLoopBackOff   6 (19s ago)   8m54s
default              pod/test-cluster-leader-2                        0/1     CrashLoopBackOff   6 (64s ago)   8m9s
```

To reproduce, use the above YAML file to create or modify a redis cluster. 

First, observe the pod fails liveness checking due to the livenessprobe setting.

<details><summary><code>kubectl describe pod/test-cluster-leader-0</code></summary><br><pre>
Warning  Unhealthy  2s    kubelet            Liveness probe failed: dial tcp 10.244.2.4:8500: connect: connection refused
</pre></details>

Wait for about a minute or so, observe that the operator keeps printing "executing command failed" errors. And your application pods keep crashing.

**Possible root cause**
The root cause of this problem might be that the redis image does not support the specified readinessProbe/livenessProbe setting. Then kubernetes tries to use the specified readinessProbe handler to check if the pod is alive or not. However, since the handler is not supported, kubernetes thinks the pod is down and keeps restarting it.

**Suggested Fix**
The operator should check if the readinessProbe/livenessProbe is supported by the application image. It should only allow the users to change the handler to the supported ones.
