### ISSUE TITLE
TLS config only gets plumbed through for clusters, but not standalone redis instances

### ISSUE THREAD

**Issue by hfinucane** [OT-CONTAINER-KIT/redis-operator#303]
**What version of redis operator are you using?**

quay.io/opstree/redis-operator:v0.11.0

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
</pre></details>

**What did you do?**
After installing redis-operator with helm, I `kubectl apply`-d this YAML-
```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-standalone
spec:
  dnsNames:
  - redis-standalone.default.svc
  - redis-standalone.default.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: redis-standalone
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
spec:

  TLS:
    ca: ca.crt # docs have this as ca.key and say that will work with cert-manager, but that seems wrong
    cert: tls.crt
    key: tls.key
    secret:
      secretName: redis-standalone

  kubernetesConfig:
    # Docs have v6.2.5 but that doesn't support TLS
    image: quay.io/opstree/redis:6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi

  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi

  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```

**What did you expect to see?**

TLS configured for redis

**What did you see instead?**

No TLS configured for redis. It's not in the config-
```
❯ kubectl exec -it redis-standalone-0 -- cat /etc/redis/redis.conf
bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis.pid
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
dir /data
```
It's not in the statefulset's environment -
```
      containers:
      - env:
        - name: PERSISTENCE_ENABLED
          value: "true"
        - name: REDIS_ADDR
          value: redis://localhost:6379
        - name: SERVER_MODE
          value: standalone
        - name: SETUP_MODE
          value: standalone
```

If I change the kind to `RedisCluster` and add `clusterSize: 3` to the spec, it works, so I'm pretty sure that this is something missing from the Redis standalone stuff that's in the Redis cluster stuff.
