### ISSUE TITLE
How the redis cluster works when it has an external config

### ISSUE THREAD

**Issue by zmrdltl** [OT-CONTAINER-KIT/redis-operator#316]
**What version of redis-operator are you using?**
redis-operator version: v0.9.0

** what i did **
Created a RedisCluster based on yaml in /example/external_config.

1. make configmap.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-external-config
data:
  redis-external.conf: |
    bind 0.0.0.0
    protected-mode yes
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis.pid
    cluster-enabled yes
    cluster-node-timeout 5000
    cluster-require-full-coverage no
    cluster-migration-barrier 1
    cluster-config-file /data/nodes.conf
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfilename "appendonly.aof"
    dir /data
    tcp-keepalive 400
    slowlog-max-len 158 
    stream-node-max-bytes 2048
```

2. make configmap2.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-external-config2
data:
  redis-external.conf: |
    bind 0.0.0.0
    protected-mode yes
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis.pid
    cluster-enabled yes
    cluster-node-timeout 5000
    cluster-require-full-coverage no
    cluster-migration-barrier 1
    cluster-config-file /data/nodes.conf
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfilename "appendonly.aof"
    dir /data
    tcp-keepalive 200
    slowlog-max-len 100
    stream-node-max-bytes 2048
```
4. make cluster.yaml
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config2
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```

5. exec redis-cluster-leader-0 pod's container
Can see folder named external.conf.d
![image](https://user-images.githubusercontent.com/22141521/183402164-737d2021-7265-48c5-abc9-94bfa5011b0d.png)

You can see that the redis-external-config of redis-cluster-leader has been successfully injected.
```bash
bash-4.4# cd external.conf.d/
bash-4.4# ls
redis-external.conf
bash-4.4# cat redis-external.conf 
bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis.pid
cluster-enabled yes
cluster-node-timeout 5000
cluster-require-full-coverage no
cluster-migration-barrier 1
cluster-config-file /data/nodes.conf
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
dir /data
tcp-keepalive 400
slowlog-max-len 158 
stream-node-max-bytes 2048
```
6. exec redis-cluster-follower-0 pod's container
You can see that the redis-external-config2 of redis-cluster-follower has been successfully injected.
```bash
bash-4.4# ls
external.conf.d  redis.conf       sentinel.conf
bash-4.4# cd external.conf.d/
bash-4.4# ls
redis-external.conf
bash-4.4# cat redis-external.conf 
bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis.pid
cluster-enabled yes
cluster-node-timeout 5000
cluster-require-full-coverage no
cluster-migration-barrier 1
cluster-config-file /data/nodes.conf
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
dir /data
tcp-keepalive 200
slowlog-max-len 100
stream-node-max-bytes 2048
```
If there is an external config, the code for volumemounting with the folder name exists in k8utils/statefulset.go line 202.
That is, after external config setting, redis.conf and redis-external.conf exist at the same time. In this case, is it set to ignore `redis.conf` and follow only `redis-external.conf` setting?
