### ISSUE TITLE
Make it possible to control serviceType

### ISSUE THREAD

**Issue by davidkarlsen** [OT-CONTAINER-KIT/redis-operator#317]
**Is your feature request related to a problem? Please describe.**
Operator used to expose a serviceType field, so that you could expose redis as a LoadBalancer, but for unknown reasons this was removed in newer versions.

**Describe the solution you'd like**
Be able to control the serviceType (as well as annotations on the service, in order to use external-dns)

**Describe alternatives you've considered**
Run helm chart instead, but an operator is preferrable.

**What version of redis-operator are you using?**
redis-operator version: v0.11.0

**Additional context**

**Comment by davidkarlsen** [comment]
@iamabhishek-dubey any update? After 0.13 this fails:
```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
  namespace: redis
spec:
  #redisConfig:
  #  additionalRedisConfig: someconfigmap
  kubernetesConfig:
    redisSecret:
      name: redis-standalone
      key: password
    serviceType: LoadBalancer
    image: 'quay.io/opstree/redis:v6.2.5'
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:2.0'
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
```

due to:

```shell
Redis/redis/redis-standalone dry-run failed, error: failed to create typed patch object (redis/redis-standalone; [redis.redis.opstreelabs.in/v1beta1](http://redis.redis.opstreelabs.in/v1beta1), Kind=Redis): .spec.kubernetesConfig.serviceType: field not declared in schema
```
