### ISSUE TITLE
Missing prometheus.io/scrape: "true" and prometheus.io/port: "9121" after cluster installation via Helm

### ISSUE THREAD

**Issue by armujahid** [OT-CONTAINER-KIT/redis-operator#336]
**What version of redis operator are you using?**

redis-operator version: v0.11.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**

1. Installed operator using 
```
helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
helm upgrade -i redis-operator ot-helm/redis-operator -n redis-operator --create-namespace
```
2. Installed redis cluster (with redis exporters) using Helm with these values
```
redisCluster:
  clusterSize: 3
  # redisSecret:
  #   secretName: redis-secret
  #   secretKey: password
  leader:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: disktype
      #         operator: In
      #         values:
      #         - ssd
  follower:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: disktype
      #         operator: In
      #         values:
      #         - ssd
  resources: {}
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

#labels:
#  foo: bar
#  test: echo

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
  env:
  - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
    value: "true"

storageSpec:
  volumeClaimTemplate:
    spec:
      # storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  #   selector: {}

```

**What did you expect to see?**
Following two annotations were missing from `redis-cluster-leader` and `redis-cluster-follower` services that were exposing redis-exporter.
```
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
``` 

1) As per [README.md ](https://github.com/OT-CONTAINER-KIT/redis-operator#monitoring-with-prometheus) these should already exist in both of these services. How to ensure that these annotations are automatically added via Helm?

**What did you see instead?**
These annotations were missing and I had to manually add those in both services to make grafana dashboard work. Note that I am not using prometheus operator.
