### ISSUE TITLE
Does have anyway to specify  nodePort?

### ISSUE THREAD

**Issue by zengzhengrong** [OT-CONTAINER-KIT/redis-operator#375]
Exposing Service specify nodePort
```
externalService:
  enabled: true
  serviceType: NodePort
  port: 6379
  nodePort: 30379
```
