### ISSUE TITLE
Cluster without persistence get's not created

### ISSUE THREAD

**Issue by alfsch** [OT-CONTAINER-KIT/redis-operator#382]
<!-- Please answer these questions before submitting your bug report. Thanks! -->

**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version:

v0.12.0

**Does this issue reproduce with the latest release?**

dont't know since v0.13.0 has the crashing issue

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-26T15:19:38Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
applied following resource

```
kind: RedisCluster
metadata:
  name: redis-cluster1
  namespace: harbor
spec:
  clusterSize: 1
  clusterVersion: v7
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
  persistenceEnabled: false
  redisExporter:
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: IfNotPresent
  redisFollower:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    pdb:
      enabled: true
      maxUnavailable: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    replicas: 3
  redisLeader:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    pdb:
      enabled: true
      maxUnavailable: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    replicas: 3
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
```


**What did you expect to see?**

a cluster without persistence

**What did you see instead?**
Two crashing pods

```
│ harbor                 redis-cluster1-leader-0                                  ●     0/1               11 CrashLoopBackOff      
│ harbor                 redis-cluster1-follower-0                                ●     0/1               11 CrashLoopBackOff
```
With following log output

```
│ Redis is running without password which is not recommended                                                                                                                                                                                     │
│ sed: /data/nodes.conf: No such file or directory                                                                                                                                                                                               │
│ Running without persistence mode                                                                                                                                                                                                               │
│ Starting redis service in cluster mode.....                                                                                                                                                                                                    │
│ 17:C 23 Nov 2022 12:41:37.847 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo                                                                                                                                                                  │
│ 17:C 23 Nov 2022 12:41:37.847 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=17, just started                                                                                                                                │
│ 17:C 23 Nov 2022 12:41:37.847 # Configuration loaded                                                                                                                                                                                           │
│ 17:M 23 Nov 2022 12:41:37.848 * monotonic clock: POSIX clock_gettime                                                                                                                                                                           │
│ 17:M 23 Nov 2022 12:41:37.848 # Can't open /data/nodes.conf in order to acquire a lock: Permission denied                                                                                                                                      │
│ Stream closed EOF for harbor/redis-cluster1-leader-0 (redis-cluster1-leader)      ```

**Comment by enenum** [comment]
the last three lines of your yaml:
```
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
```
Set for `fsGroup: 0` and `runAsUser: 0` to get around it. Of course that means you are running as root - and it might not be desirable for you. I read that it was about SELINUX - I had it at permissive and even  disabled and the problem persisted.

**Comment by iamabhishek-dubey** [comment]
```yaml
  clusterVersion: v7
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
```

clusterVersion and image version are not matching. Ideally, it should match.
