### ISSUE TITLE
Compatibility with GCP Managed Prometheus for redis exporter.

### ISSUE THREAD

**Issue by anish749** [OT-CONTAINER-KIT/redis-operator#386]
## Problem
We running on GCP, with GKE + Google Managed Prometheus (GMP). The managed version of Prometheus from Google, works slightly differently and isn't scraping the metrics from the redis exporter.

This is because the ports for metrics are exposed via the Service. Prometheus has a `ServiceMonitor`, which works as intended, however in GMP, [they have](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-servicemonitor) `PodMonitoring` instead of `ServiceMonitor` like OSS Promethus. and their docs suggest translating `ServiceMonitor` to `PodMonitoring` . Since the named ports aren't defined in the pod template, `PodMonitoring` in GMP isn't able to get to this port and scrape the metrics.

## Proposed Solution

Expose the named port of the `redis-exporter` in the StatefulSet pod template alongside the `ServicePorts`.

## Workaround / alternative solution

Use a proxy that is a pod and it exposes the `redis-exporter` port and proxies it to the service port.
 - create an envoy proxy that has the `redis-exporter` port defined in the pod template, and it proxies 9121 port of the service.
 - try to scrape from the proxy deployment using `PodMonitoring` from Google's Prometheus.

Proxy config used is as follows:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-proxy
  labels:
    app: redis-exporter-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter-proxy
  template:
    metadata:
      labels:
        app: redis-exporter-proxy
    spec:
      containers:
      - name: envoy
        image: redis-exporter-proxy
        ports:
        - name: redis-exporter
          containerPort: 9121 # redis exporter port
```

envoy config
```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 9121 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: redis_exporter
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: 
                  cluster: redis_exporter
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router


  clusters:
  - name: redis_exporter
    connect_timeout: 0.25s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: redis_pod
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: spq-redis, port_value: 9121 }
```

**What version of redis-operator are you using?**

redis-operator version: v0.13

**Additional context**

Happy to create a PR to add the ports to the pod template if this is a good idea.
