### ISSUE TITLE
Cluster Recovery Failure 

### ISSUE THREAD

**Issue by bellomdanbinta** [OT-CONTAINER-KIT/redis-operator#388]
We have a kubernates redis cluster of 6 nodes, 3 masters and 3 followers. We have installed the operator starting from v0.9.0.
The cluster was having problem recovering from a failed node with the given error message "Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.",
We followed the failover test guides from the docs https://ot-container-kit.github.io/redis-operator/guide/failover.html

We then upgraded the operator to v0.11.0, then to v0.12.0 and finally to v0.13.0 and for every step we tried the test but still getting the same problem.
```
NAME            CSV                      APPROVAL   APPROVED
install-cnbbp   redis-operator.v0.12.0   Manual     true
install-jbcxg   redis-operator.v0.11.0   Manual     true
install-lzmvw   redis-operator.v0.9.0    Manual     true
install-mxtzr   redis-operator.v0.13.0   Manual     false
```

**What version of redis operator are you using?**
redis operator version v0.13.0

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```
```
{"level":"error","ts":1669631965.1686046,"logger":"controller_redis","msg":"Could not execute command","Request.RedisManager.Namespace":"the-namespace-name","Request.RedisManager.Name":"redis","Command":["redis-cli","--cluster","create","10.244.4.65:6379","10.244.1.46:6379","10.244.6.188:6379","--cluster-yes"],"Output":"[ERR] Node 10.244.1.46:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.\n","Error":"","error":"command terminated with exit code 1","stacktrace":"redis-operator/k8sutils.ExecuteRedisClusterCommand\n\t/workspace/k8sutils/redis.go:116\nredis-operator/controllers.(*RedisClusterReconciler).Reconcile\n\t/workspace/controllers/rediscluster_controller.go:123\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```

redis-operator version:  v0.13.0

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.19) exceeds the supported minor version skew of +/-1
```
</pre></details>

**What did you do?**

After following the installation procedure in version v0.9.0 and applying the failover test, it did not work, rather we're getting "Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0."  
Then we follow the below step to upgrade to other latest version.

1. kubectl -n operators delete subs my-redis-operator
2. kubectl -n operators delete csv redis-operator.v0.9.0
3. kubectl -n operators get operators.operators.coreos.com
4. kubectl apply -f redis-operator-v0.11.0-sub.yaml

**Subscription YAML file**

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-redis-operator
  namespace: operators
spec:
  channel: stable
  name: redis-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Manual
  startingCSV: redis-operator.v0.11.0

5. kubectl -n operators patch installplan <install-name> -p '{"spec":{"approved":true}}' --type merge
6. After the above steps the cluster didn't come up so we have to fix it using the script below.
```

```
kubectl -n <namespace> patch statefulset/redis-leader --patch '{
	"spec": {
		"template": {
			"spec": {
				"containers": [{
					"livenessProbe": {
						"exec": {
							"command": ["bash", "/usr/bin/healthcheck.sh"]
						},
						"failureThreshold": 5,
						"initialDelaySeconds": 15,
						"periodSeconds": 15,
						"successThreshold": 1,
						"timeoutSeconds": 5
					},
					"readinessProbe": {
						"exec": {
							"command": ["bash", "/usr/bin/healthcheck.sh"]
						},
						"failureThreshold": 5,
						"initialDelaySeconds": 15,
						"periodSeconds": 15,
						"successThreshold": 1,
						"timeoutSeconds": 5
					},
					"name": "redis-leader"
				}]
			}
		}
	}
}'

kubectl -n <namespace> patch statefulset/redis-follower --patch '{
	"spec": {
		"template": {
			"spec": {
				"containers": [{
					"livenessProbe": {
						"exec": {
							"command": ["bash", "/usr/bin/healthcheck.sh"]
						},
						"failureThreshold": 5,
						"initialDelaySeconds": 15,
						"periodSeconds": 15,
						"successThreshold": 1,
						"timeoutSeconds": 5
					},

					"readinessProbe": {
						"exec": {
							"command": ["bash", "/usr/bin/healthcheck.sh"]
						},
						"failureThreshold": 5,
						"initialDelaySeconds": 15,
						"periodSeconds": 15,
						"successThreshold": 1,
						"timeoutSeconds": 5
					},
					"name": "redis-follower"
				}]
			}
		}
	}
}'
```
**Cluster YAML**

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis
  namespace: the-namespace-name
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 8Gi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config
```

**What did you expect to see?**
Using the command below I was expecting the deleted master to join the cluster but it failed.

```$> kubectl exec -it redis-leader-1 -n <namespace> -- redis-cli cluster nodes```

```
Defaulted container "redis-leader" out of: redis-leader, redis-exporter
87e92b06bf62bc54cdca0c700396329a81b5b74a 10.244.6.184:6379@16379 master - 0 1669647901000 5 connected 0-5460
a7f0174a19d1b1d0c5702e5217cd8ecdd438a29e 10.244.1.47:6379@16379 slave 74325052e04c42943d243d3abc7900f7e7e8bce7 0 1669647902440 2 connected
e3bd85dc92c2422575e3c610a436804574f838ff 10.244.6.188:6379@16379 master - 0 1669647901938 3 connected 10923-16383
7c46e249126f5009dc3df3998efa8b24b23e0dbb 10.244.4.227:6379@16379 slave e3bd85dc92c2422575e3c610a436804574f838ff 0 1669647901000 3 connected
c7d9ccb703287adf0b561b96ffd115b871a5bb43 10.244.5.128:6379@16379 master,fail - 1669631895578 1669631893000 1 connected
74325052e04c42943d243d3abc7900f7e7e8bce7 10.244.1.46:6379@16379 myself,master - 0 1669647901000 2 connected 5461-10922
```

**What did you see instead?**

```
c7d9ccb703287adf0b561b96ffd115b871a5bb43 10.244.5.128:6379@16379 master,fail - 1669631895578 1669631893000 1 connected
```

**Comment by chenghongxi** [comment]
能看下你的整体yaml文件么?

**Comment by bellomdanbinta** [comment]
Thanks a lot for your comment, I really don't understand what you mean as the comment is in Chinese and when I translated it this is what is says "Can you take a look at your overall yaml file?". Below I'm adding the complete YAML file if you can direct me to where you see any problem it will be appreciated.

```
apiVersion: v1
kind: Namespace
metadata:
  name: the-namespace-name

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-external-config
  namespace: the-namespace-name
data:
  redis-external.conf: |
    appendonly no

---

apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis
  namespace: the-namespace-name
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 8Gi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config
```
