### ISSUE TITLE
Redis Cluster fails after restart any redis pod

### ISSUE THREAD

**Issue by ahmedsamer** [OT-CONTAINER-KIT/redis-operator#39]
Hello, 

My Redis cluster fails after every time I delete one of its pods (or if it's restarted for any other reason)
and then it fails to re-initiate the cluster or even add the restarted pod

```
021-02-08T15:05:01.321Z        INFO    controller_redis        Redis replication creation command is   {"Request.Namespace": "redis", "Request.Name": "redis", "Command": ["redis-cli", "--cluster", "add-node", "10.244.6.71:6379", "10.244.1.121:6379", "--cluster-slave"]}
2021-02-08T15:05:02.006Z        ERROR   controller_redis        Could not execute command       {"Request.Namespace": "redis", "Request.Name": "redis", "error": "command terminated with exit code 1"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
redis-operator/k8sutils.ExecuteCommand
        /workspace/k8sutils/redis.go:192
redis-operator/k8sutils.ExecuteRedisReplicationCommand
        /workspace/k8sutils/redis.go:92
redis-operator/controllers.(*RedisReconciler).Reconcile
        /workspace/controllers/redis_controller.go:100
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99
```

and this is my configs for the cluster

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis
  namespace: redis
spec:
  global:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 10Gi
      requests:
        cpu: 500m
        memory: 5Gi
  master:
    redisConfig: {}
    service:
      type: ClusterIP
  mode: cluster
  redisConfig: {}
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  service:
    type: ClusterIP
  size: 3
  slave:
    redisConfig: {}
    service:
      type: ClusterIP
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: glusterfs
```

**Comment by iamabhishek-dubey** [comment]
I tested this scenario and I don't see this issue, have you validated using `redis-cli` command.

**Comment by ahmedsamer** [comment]
Hello, 
  Here is how I reproduce this in another cluster (installed using kind) 
  I have this issue in two clusters (installed using kubeadm)

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis
  namespace: redis
spec:
  global:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
  master:
    redisConfig: {}
    service:
      type: ClusterIP
  mode: cluster
  redisConfig: {}
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  service:
    type: ClusterIP
  size: 3
  slave:
    redisConfig: {}
    service:
      type: ClusterIP
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
```
```
$ kubectl --namespace redis get pod -o wide
NAME             READY   STATUS        RESTARTS   AGE     IP            NODE                 NOMINATED NODE   READINESS GATES
redis-master-0   2/2     Running       0          6m8s    10.244.0.16   kind-control-plane   <none>           <none>
redis-master-1   2/2     Running       0          5m19s   10.244.0.20   kind-control-plane   <none>           <none>
redis-master-2   2/2     Running       0          4m50s   10.244.0.25   kind-control-plane   <none>           <none>
redis-slave-0    2/2     Running       0          6m8s    10.244.0.17   kind-control-plane   <none>           <none>
redis-slave-1    2/2     Running       0          5m16s   10.244.0.21   kind-control-plane   <none>           <none>
redis-slave-2    2/2     Running       0          4m53s   10.244.0.23   kind-control-plane   <none>           <none>
```

```
$ kubectl --namespace redis exec -it redis-master-0 -c redis-master -- redis-cli cluster nodes
79c663c6ee8f09ec9ad4f275f12a7d1277659335 10.244.0.25:6379@16379 master - 0 1612862224850 3 connected 10923-16383
cc40795a116601c6ca3856ef20171a17a68e10a5 10.244.0.16:6379@16379 myself,master - 0 1612862224000 1 connected 0-5460
fc6fd1a2c5715bb1a6ad968a3982efffaf2d342b 10.244.0.23:6379@16379 slave 79c663c6ee8f09ec9ad4f275f12a7d1277659335 0 1612862225000 3 connected
332f137889180d3ef1c99a721ee063b45cb22e1d 10.244.0.20:6379@16379 master - 0 1612862226356 2 connected 5461-10922
211f1581d783a05eca98c35aac7bf92ab16091b6 10.244.0.17:6379@16379 slave cc40795a116601c6ca3856ef20171a17a68e10a5 0 1612862224348 1 connected
4c949aeb29c655c84a0b124bdaccc590b0d549ad 10.244.0.21:6379@16379 slave 332f137889180d3ef1c99a721ee063b45cb22e1d 0 1612862226054 2 connected
```

```
kubectl --namespace redis exec -it redis-master-0 -c redis-master -- redis-cli -c set name ahmedsamer
OK

# add data to the cluster
$ kubectl --namespace redis exec -it redis-master-0 -c redis-master -- redis-cli -c get name 
"ahmedsamer"
```

```
$ kubectl --namespace redis delete pod redis-master-1
pod "redis-master-1" deleted

$ kubectl --namespace redis get pod -o wide
NAME             READY   STATUS        RESTARTS   AGE     IP            NODE                 NOMINATED NODE   READINESS GATES
redis-master-0   2/2     Running       0          6m40s   10.244.0.16   kind-control-plane   <none>           <none>
redis-master-1   2/2     Running       0          30s   10.244.0.27   kind-control-plane   <none>           <none>
redis-master-2   2/2     Running       0          5m12s   10.244.0.25   kind-control-plane   <none>           <none>
redis-slave-0    2/2     Running       0          7m40s   10.244.0.17   kind-control-plane   <none>           <none>
redis-slave-1    2/2     Running       0          5m48s   10.244.0.21   kind-control-plane   <none>           <none>
redis-slave-2    2/2     Running       0          5m25s   10.244.0.23   kind-control-plane   <none>           <none>
```

and here is the mos important part
```
$ kubectl --namespace redis exec -it redis-master-0 -c redis-master -- redis-cli cluster nodes
79c663c6ee8f09ec9ad4f275f12a7d1277659335 10.244.0.25:6379@16379 master - 0 1612864316985 3 connected 10923-16383
cc40795a116601c6ca3856ef20171a17a68e10a5 10.244.0.16:6379@16379 myself,master - 0 1612864316000 1 connected 0-5460
fc6fd1a2c5715bb1a6ad968a3982efffaf2d342b 10.244.0.23:6379@16379 slave 79c663c6ee8f09ec9ad4f275f12a7d1277659335 0 1612864315000 3 connected
332f137889180d3ef1c99a721ee063b45cb22e1d 10.244.0.20:6379@16379 master,fail - 1612862288562 1612862286555 2 connected
211f1581d783a05eca98c35aac7bf92ab16091b6 10.244.0.17:6379@16379 slave cc40795a116601c6ca3856ef20171a17a68e10a5 0 1612864316582 1 connected
4c949aeb29c655c84a0b124bdaccc590b0d549ad 10.244.0.21:6379@16379 master - 0 1612864316000 4 connected 5461-10922
```

Now `redis-master-1` marked as failed and never being added to the cluster, but will keep getting data because we are using the service `redis-master`

```
$ kubectl --namespace redis exec -it redis-master-1 -c redis-master -- redis-cli cluster nodes
61d300afa441b55a26493e86ab7535b62e238ac6 10.244.0.27:6379@16379 myself,master - 0 0 0 connected 5798

$ kubectl --namespace redis exec -it redis-master-1 -c redis-master -- redis-cli -c set name AnotherName
OK
```

Now using another pod to test
```
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"ahmedsamer"
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"ahmedsamer"
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"ahmedsamer"
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"AnotherName"
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"ahmedsamer"
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"AnotherName"
$ kubectl exec -it redis -- /usr/local/bin/redis-cli -c -h redis-master.redis get name
"ahmedsamer"

```
