### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by davidkarlsen** [OT-CONTAINER-KIT/redis-operator#394]
**What version of redis operator are you using?**

0.13.0

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version:

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

```yaml
cat redis-cluster.yaml 
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  labels:
    test: test
  name: redis-cluster
  namespace: jfr-dev
spec:
  clusterSize: 3
  clusterVersion: v7
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
    updateStrategy: {}
  redisExporter:
    image: ""
  redisFollower:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  redisLeader:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```

**What did you expect to see?**

a running cluster, or a validation error of the CR.

**What did you see instead?**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d0 pc=0x140b367]
goroutine 601 [running]:
redis-operator/k8sutils.generateRedisClusterContainerParams(0xc000227b80, 0xc000b5c510, 0xc000b5c4f8)
	/workspace/k8sutils/redis-cluster.go:60 +0xe7
redis-operator/k8sutils.RedisClusterSTS.CreateRedisClusterSetup({{0x172981b, 0x6}, 0x0, 0x0, 0xc000b5c510, 0xc000b5c4f8}, 0xc000227b80)
	/workspace/k8sutils/redis-cluster.go:161 +0x3fa
redis-operator/k8sutils.CreateRedisLeader(0xc000227b80)
	/workspace/k8sutils/redis-cluster.go:112 +0xa9
redis-operator/controllers.(*RedisClusterReconciler).Reconcile(0xc0000a2c60, {0xc000db9350, 0x1560440}, {{{0xc0001b1a36, 0x166b4a0}, {0xc0001b1a40, 0x30}}})
	/workspace/controllers/rediscluster_controller.go:73 +0x345
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0004c4160, {0x1945c38, 0xc000db9350}, {{{0xc0001b1a36, 0x166b4a0}, {0xc0001b1a40, 0x413a34}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004c4160, {0x1945b90, 0xc0006cd8c0}, {0x15b5ca0, 0xc000c194a0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004c4160, {0x1945b90, 0xc0006cd8c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```
