### ISSUE TITLE
After redis operator upgrade the operator crash-loops with SIGSEGV

### ISSUE THREAD

**Issue by leonsteinhaeuser** [OT-CONTAINER-KIT/redis-operator#414]
**What version of redis operator are you using?**

```shell
image: quay.io/opstree/redis-operator:v0.13.0
```

redis-operator version:

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
clientVersion:
  buildDate: "2022-11-09T13:36:36Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2021-12-15T14:46:22Z"
  compiler: gc
  gitCommit: 4a3b558c52eb6995b3c5c1db5e54111bd0645a64
  gitTreeState: clean
  gitVersion: v1.21.8
  goVersion: go1.16.12
  major: "1"
  minor: "21"
  platform: linux/amd64
</pre></details>

**What did you do?**

I modified my old existing cluster definition and added an annotation to it (`redis.opstreelabs.in/recreate-statefulset: "true"`).

Cluster definition:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  annotations:
    redis.opstreelabs.in/recreate-statefulset: "true"
  labels:
    cluster-name: my-redis-deployment
  name: my-redis-deployment
  namespace: my-redis-namespace
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 900m
        memory: 2000Mi
      requests:
        cpu: 900m
        memory: 2000Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisFollower:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usage
              operator: In
              values:
              - my-redis-node
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: my-redis-deployment
              operator: In
              values:
              - my-redis-deployment-follower
          topologyKey: kubernetes.io/hostname
    livenessProbe:
      exec:
        command:
        - bash
        - /usr/bin/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    pdb:
      enabled: true
      minAvailable: 1
    readinessProbe:
      exec:
        command:
        - bash
        - /usr/bin/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    redisConfig:
      additionalRedisConfig: my-redis-deployment-config
  redisLeader:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usage
              operator: In
              values:
              - my-redis-node
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: cluster-name
              operator: In
              values:
              - my-redis-deployment
          topologyKey: kubernetes.io/hostname
    livenessProbe:
      exec:
        command:
        - bash
        - /usr/bin/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    pdb:
      enabled: true
      minAvailable: 1
    readinessProbe:
      exec:
        command:
        - bash
        - /usr/bin/healthcheck.sh
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    redisConfig:
      additionalRedisConfig: my-redis-deployment-config
  storage:
    volumeClaimTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
      status: {}
  tolerations:
  - effect: NoSchedule
    key: usage
    operator: Equal
    value: my-redis-node
```

**What did you expect to see?**

Not a crash-looping controller/operator.

**What did you see instead?**

A crash-loop of the operator with the following error message.

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140e54b]

goroutine 365 [running]:
redis-operator/k8sutils.CreateMultipleLeaderRedisCommand(0xc000a18780)
	/workspace/k8sutils/redis.go:78 +0x16b
redis-operator/k8sutils.ExecuteRedisClusterCommand(0xc000a18780)
	/workspace/k8sutils/redis.go:103 +0xfc
redis-operator/controllers.(*RedisClusterReconciler).Reconcile(0xc0001dc270, {0xc0009adbf0, 0x1560440}, {{{0xc000610468, 0x166b4a0}, {0xc000610450, 0x30}}})
	/workspace/controllers/rediscluster_controller.go:130 +0xbde
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00064e4d0, {0x1945c58, 0xc0009adbf0}, {{{0xc000610468, 0x166b4a0}, {0xc000610450, 0x413a34}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00064e4d0, {0x1945bb0, 0xc0008896c0}, {0x15b5ca0, 0xc000117780})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00064e4d0, {0x1945bb0, 0xc0008896c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```
