### ISSUE TITLE
Creating a password-protected cluster fails the health/readinessprobe

### ISSUE THREAD

**Issue by wombat** [OT-CONTAINER-KIT/redis-operator#416]
**What version of redis operator are you using?** 0.13

**Does this issue reproduce with the latest release?**  yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$  oc version
Client Version: 4.10.0-202206270836.p0.g45460a5.assembly.stream-45460a5
Server Version: 4.10.47
Kubernetes Version: v1.23.12+8a6bfe4

</pre></details>

**What did you do?**

I created a redis cluster using this example: https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.13.0/example/password_protected/clusterd.yaml

I just changed the `runAsUser` and `fsGroup` to the correct OpenShift group.

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  finalizers:
    - redisClusterFinalizer
  name: redis
  namespace: redis-test
spec:
  persistenceEnabled: true
  redisLeader:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v7.0.5'
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: redis-secret
    updateStrategy: {}
  securityContext:
    fsGroup: 1000430000
    runAsUser: 1000430000
  redisFollower:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  clusterSize: 3
  storage:
    volumeClaimTemplate:
      metadata: {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  redisExporter:
    image: 'quay.io/opstree/redis-exporter:v1.44.0'
  clusterVersion: v7
```

**What did you expect to see?**
A working redis cluster with password protection

**What did you see instead?**
This message in the event log:
```
Readiness probe failed: AUTH failed: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a an authentication password for the default user. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside. Error: Connection reset by peer
```

I had a look at the `healthcheck.sh` and when just executing `redis-cli ping` I get a `PONG` response - when adding the hostname manually I get the same error as above.

**Comment by hoanbc** [comment]
same issue

**Comment by shubham-cmyk** [comment]
Let met check this out

**Comment by hoanbc** [comment]
i did see an error.
redis default running with id 1000. if you set id (runAsUser) different, it will show you not have permission write to /etc/redis/redis.conf
```yml
securityContext:
    fsGroup: 1000430000
    runAsUser: 1000430000
```
solution: set scc and deploy file to runAsUser 1000
```yml
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  name: scc-redis
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - 'system:serviceaccount:testvn-redis:builder'
  - 'system:serviceaccount:testvn-redis:default'
  - 'system:serviceaccount:testvn-redis:redis'
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
```
