### ISSUE TITLE
Enable set replicas for redis standalone

### ISSUE THREAD

**Issue by romga** [OT-CONTAINER-KIT/redis-operator#418]
**Is your feature request related to a problem? 
It would be great if we can control the replicas of redis standalone as well.
Sometimes, i would like to set the replica to be 0 (for example when i dont need the pods to be up, but i still want to keep the data)
If we would have the option to control the replicas from outside, or declare if the pods should be up or not, it can help us a lot.

**Describe the solution you'd like**
The solution i would like is to control the replicas of redis standalone as part of the operator.
for example:
```
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis
spec:
  **replicas: 0**
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi%
```
in this example, i have added a new filed, calls replicas, which enable me to control the number of the replicas,
and when i dont need the redis to be up and running, i can just change the replicas to 0

**What version of redis-operator are you using?**

redis-operator version: 0.13.0

**Additional context**
