### ISSUE TITLE
PVC name repeated too long

### ISSUE THREAD

**Issue by muicoder** [OT-CONTAINER-KIT/redis-operator#438]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: v0.14.0

**Additional context**

cr.Name: `test-cluster`
```yaml
pvcName:
  Origin: test-cluster-follower-test-cluster-follower-0
  Improved: data-test-cluster-follower-0
```
