### ISSUE TITLE
Support reading password from a secret

### ISSUE THREAD

**Issue by jessebye** [OT-CONTAINER-KIT/redis-operator#44]
We prefer not to have our redis password in plaintext in the CR, and would instead like to pass it by a secret ref. Could this functionality be added?

Example:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis
spec:
  global:
    passwordSecretRef: my-password
```

Then elsewhere a secret is defined:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-password
type: Opaque
data:
  password: dGVzdA==
```
