### ISSUE TITLE
AdditionalRedisConfig does not work

### ISSUE THREAD

**Issue by xuziheng1002** [OT-CONTAINER-KIT/redis-operator#471]
This is my redis-replication release config:
```
redisReplication:
  clusterSize: 3
  image: harbor-server/prd/redis
  tag: v6.2.5
  imagePullPolicy: IfNotPresent
  redisSecret:
    secretName: redis-secret
    secretKey: password
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 16Gi
  redisConfig:
    additionalRedisConfig: redis-external-config

externalConfig:
  enabled: true
  data: |
    databases 32
    maxmemory 12gb
    maxmemory-policy noeviction
    maxclients 1000
externalService:
  enabled: true
  serviceType: NodePort
  port: 6379

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  image: harbor-server/prd/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
sidecars: []
nodeSelector: {}
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: my-nas
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi
securityContext:
  runAsUser: 1000
  fsGroup: 1000

affinity: {}
```

And this is redis-additional.conf created by configmap:
```
apiVersion: v1
data:
  redis-additional.conf: |
    databases 32
    maxmemory 12gb
    maxmemory-policy noeviction
    maxclients 1000
kind: ConfigMap
...
```

but `databases 32` config item does not works
```
192.168.1.74:32945> select 17
(error) ERR DB index is out of range
```

how can I solve it?
