### ISSUE TITLE
Failing leader node leads to connection refused errors

### ISSUE THREAD

**Issue by sondrelg** [OT-CONTAINER-KIT/redis-operator#477]
Hi!

First of all thanks for creating and maintaining the redis operator and the cluster charts :bow: 

<details>
<summary><b>Version info & chart configuration</b></summary>

This is our cluster settings:

```yaml
redis-cluster:
  redisCluster:
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

  externalConfig:
    enabled: true
    data: |
      maxmemory 1gb
      maxmemory-policy allkeys-lru

  pdb:
    enabled: true
    maxUnavailable: 1

  serviceMonitor:
    enabled: true

  redisExporter:
    enabled: true

  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 6Gi
```

**What version of redis operator are you using?**

0.14 (latest)

**What operating system and processor architecture are you using (`kubectl version`)?**

bottlerocket, x86_64

</details>

## Background

We've recently deployed a redis cluster (3 leaders, 3 followers), and today when one of our leader pods were moved to a new node the entire cluster "went down". 

I suspect there might be an error in how we've set things up, so I'm really only here in the hope that we've made a basic config error that will be easy for you to spot :crossed_fingers: 

## Incident

Some of our pods seem to have been moved around a bit, resulting in these logs from the redis cluster:

```
10:S 31 Mar 2023 09:22:50.179 * FAIL message received from 5be30416f3ed156c9f53de5350792367e2f0dd36 about 4d1b11d5e12cbb8e52927ce8953eabdca236c4ea
10:S 31 Mar 2023 09:22:50.179 * FAIL message received from 5be30416f3ed156c9f53de5350792367e2f0dd36 about 4d1b11d5e12cbb8e52927ce8953eabdca236c4ea
10:S 31 Mar 2023 09:28:58.144 # Address updated for node 4d1b11d5e12cbb8e52927ce8953eabdca236c4ea, now 10.0.10.207:6379
10:S 31 Mar 2023 09:28:58.244 * Clear FAIL state for node 4d1b11d5e12cbb8e52927ce8953eabdca236c4ea: is reachable again and nobody is serving its slots after some time.
```
```
10:S 31 Mar 2023 09:22:51.225 * Marking node 5587dab2fade96d595dbf04787ad4135d1daf3e2 as failing (quorum reached).
10:S 31 Mar 2023 09:28:57.713 # Address updated for node 5587dab2fade96d595dbf04787ad4135d1daf3e2, now 10.0.10.174:6379
10:S 31 Mar 2023 09:28:57.723 * Clear FAIL state for node 5587dab2fade96d595dbf04787ad4135d1daf3e2: replica is reachable again.
```
```
10:S 31 Mar 2023 09:30:27.561 * FAIL message received from 4d1b11d5e12cbb8e52927ce8953eabdca236c4ea about 9825cfff33fdd56adabd415bc306fe9f72ce38b8
10:S 31 Mar 2023 09:31:15.202 # Address updated for node 9825cfff33fdd56adabd415bc306fe9f72ce38b8, now 10.0.10.16:6379
10:S 31 Mar 2023 09:31:15.228 * Clear FAIL state for node 9825cfff33fdd56adabd415bc306fe9f72ce38b8: replica is reachable again.
```

Following this we see runtime errors in our application:

```
Error 113 connecting to 10.0.10.221:6379. No route to host.
```

## Question

- We're not sure, but this almost seems like we're resolving the IP to the cluster on app start-up, and then running into problems when the cluster moves. 

    For context, we are connecting to the cluster using the  service name: `redis://<username>:<password>@<project-name>-redis-master:6379` - is this the right way to connect?

- Do you have any other suggestions for what might be wrong? We're using the [redis](https://pypi.org/project/redis/) python client to connect if that matters.
