### ISSUE TITLE
Cluster fail in default namespace

### ISSUE THREAD

**Issue by sadath-12** [OT-CONTAINER-KIT/redis-operator#485]
**Whats your configuration?**

using operator version redis:v7.0.5

for cluster using docker desktop

what did you do ? 

I applied the example manifest of redis cluster given in the repo 
then try checking the cluster state with command 

```
kubectl exec -it redis-cluster-leader-0 -- redis-cli -a Opstree@1234 cluster info

```

**What did you expect to see?**

I expected cluster state ok

**What did you see instead?**

![cluster](https://user-images.githubusercontent.com/90619459/230720848-eb971d3a-af60-4003-a6b3-a93b2a08482d.png)

Note :

This problem doesnt occur in other namespaces for me

**Comment by shubham-cmyk** [comment]
@sadath-12 
Please mention which manifest you used.

**Comment by sadath-12** [comment]
```
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: default
spec:
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  securityContext:
    runAsUser: 1000
    fsGroup: 1000 
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    redisSecret:
      name: redis-secret
      key: password
    # imagePullSecrets:
    #   - name: regcred
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
# Environment Variables for Redis Exporter
    # env:
    # - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
    #   value: "true"
    # - name: UI_PROPERTIES_FILE_NAME
    #   valueFrom:
    #     configMapKeyRef:
    #       name: game-demo
    #       key: ui_properties_file_name
    # - name: SECRET_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: mysecret
    #       key: username
#  redisLeader:
#    redisConfig:
#      additionalRedisConfig: redis-external-config
#  redisFollower:
#    redisConfig:
#      additionalRedisConfig: redis-external-config
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  # nodeSelector:
  #   kubernetes.io/hostname: minikube
  # priorityClassName:
  # Affinity:
  # Tolerations: []

```
