### ISSUE TITLE
Add labels for Redis-cluster

### ISSUE THREAD

**Issue by sondrelg** [OT-CONTAINER-KIT/redis-operator#500]
**Is your feature request related to a problem? Please describe.**

I would like to prevent co-hosting of leader/follower pairs for a redis-cluster. I don't mind if two followers are hosted on the same node, as long as:

- No leaders are hosted on the same node
- **`leader-n` isn't hosted on the same node as `follower-n`**

So for example, I imagine this would be fine:

| node1      | node2      | node3    | node4 | node5 |
|------------|------------|----------|------|--------| 
| leader-1   | leader-2   | leader-3 | -    | -      |
| follower-2 | follower-3 | -        | -    | -      |
| -          | follower-1 | -        | -    | -      |

**Describe the solution you'd like**

:heavy_check_mark:  Preventing co-hosting of leaders is already fine. We can use the `role` label.

Preventing co-hosting of _pairs_ is missing (I believe - please let me know if you there's a way I haven't thought of). I think this could be achieved using podAntiAffinity rules if the pod labels were expanded so that `follower-1` shared a label with `leader-1`. For example:

```yaml
metadata:
  labels:
    pair: 1  # <-- this would be the new label and should contain the pod count that's used in the name
    redis_setup_type: cluster
    role: follower
    statefulset.kubernetes.io/pod-name: follower-1
```

**Describe alternatives you've considered**
I haven't really considered anything else. Very open to alternative suggestions :bow: 

**What version of redis-operator are you using?**

0.14.0

**Context** 

The reason this matters is that this solution would mean I need a minimum of 3 nodes in my k8s cluster to host the redis-cluster, rather than 6.

**Comment by sondrelg** [comment]
After a bit of thinking, I came up with this as a solution for my specific case:

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      # Avoid leaders being scheduled with other leaders
      - labelSelector:
          matchExpressions:
            - key: "role"
              operator: In
              values:
                - leader
        topologyKey: "kubernetes.io/hostname"
      # Prevent leader-1 from being co-hosted with follower-1
      - labelSelector:
          matchExpressions:
            - key: "statefulset.kubernetes.io/pod-name"
              operator: In
              values:
                - project-name-follower-1
                - project-name-leader-1
        # Applied to the node-level
        topologyKey: "kubernetes.io/hostname"
      # Prevent leader-2 from being co-hosted with follower-2
      - labelSelector:
          matchExpressions:
            - key: "statefulset.kubernetes.io/pod-name"
              operator: In
              values:
                - project-name-follower-2
                - project-name-leader-2
        topologyKey: "kubernetes.io/hostname"
      # Prevent leader-3 from being co-hosted with follower-3            
      - labelSelector:
          matchExpressions:
            - key: "statefulset.kubernetes.io/pod-name"
              operator: In
              values:
                - project-name-follower-3
                - project-name-leader-3
        topologyKey: "kubernetes.io/hostname"
```

Does that seem reasonable? If there's no clear value add from adding extra labels, then please feel free to just close this - I think I'll be able to achieve what I wanted :+1:
