### ISSUE TITLE
Redis Replication with Sentinels configure empty master after statefulset rollout

### ISSUE THREAD

**Issue by omrirosner-clx** [OT-CONTAINER-KIT/redis-operator#522]
**What version of redis operator are you using?**

v0.14.0

```shell
{"level":"error","ts":1686838587.4277818,"logger":"controller_redis","msg":"Error in getting redis pod IP","Request.RedisManager.Namespace":"omri-test","Request.RedisManager.Name":"","error":"resource name may not be empty","stacktrace":"github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.getRedisReplicationMasterIP\n\t/workspace/k8sutils/redis-sentinel.go:309\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.getSentinelEnvVariable\n\t/workspace/k8sutils/redis-sentinel.go:239\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.generateRedisSentinelContainerParams\n\t/workspace/k8sutils/redis-sentinel.go:145\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.RedisSentinelSTS.CreateRedisSentinelSetup\n\t/workspace/k8sutils/redis-sentinel.go:72\ngithub.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateRedisSentinel\n\t/workspace/k8sutils/redis-sentinel.go:45\ngithub.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisSentinelReconciler).Reconcile\n\t/workspace/controllers/redissentinel_controller.go:50\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1686838587.4279523,"logger":"controller_redis","msg":"Successfully got the ip for redis","Request.RedisManager.Namespace":"omri-test","Request.RedisManager.Name":"","ip":""}
```

**What operating system and processor architecture are you using (`kubectl version`)?**

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/arm64"}

The node that the operator was running on was amd64.

**What did you do?**

We want to start using HA redis with sentinels in our k8s clusters. I finished setting everything up (replication, sentinels...), but after some testing I found out that every time I rollout all of our Redis Replication pods, either from a manual rollout restart or a change to a field in the RedisReplication custom resource, the whole setup would stop working because the sentinels and the replications would not set the correct master.

Deleting just the master pod manually worked fine, but 80% of the time, restarting all pods would cause issues.

This is probably related to the `checkAttachedSlave` function. The master redis instances would have no slaves after the restarts, and the sentinels would default back to their default IP (0.0.0.0). 

Redis replication spec:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - platform
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - test-sentinel-redis
            topologyKey: kubernetes.io/hostname
          weight: 50
  clusterSize: 3
  kubernetesConfig: {...}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  priorityClassName: datastores
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  redisExporter:
    enabled: true
    env:
      - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
        value: 'true'
    image: '<our mirror image repo>/redis-exporter:v1.45.0'
    imagePullPolicy: Always
  securityContext:
    runAsUser: 0
  tolerations:
    - effect: NoSchedule
      key: role
      operator: Equal
      value: platform
```

Redis Sentinel spec:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - platform
  clusterSize: 3
  kubernetesConfig: {...}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  priorityClassName: datastores
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  redisSentinelConfig:
    downAfterMilliseconds: '30000'
    failoverTimeout: '180000'
    masterGroupName: myMaster
    parallelSyncs: '1'
    quorum: '2'
    redisPort: '6379'
    redisReplicationName: test-sentinel-redis
  securityContext:
    runAsUser: 0
  tolerations:
    - effect: NoSchedule
      key: role
      operator: Equal
      value: platform
```

**What did you expect to see?**

After the restart, I would expect to see that the redis sentinel statefulset would be updated with the correct ENV_VARS for the master redis PORT.
I would expect the redis replicas to recognize each other as master/slaves. 

**What did you see instead?**
The redis sentinel statefulset was created with these env vars:
```
...
- name: MASTER_GROUP_NAME
  value: myMaster
- name: IP
- name: PORT
  value: "6379"
- name: QUORUM
  value: "2"
...
```
The empty IP would be configured for the redis instances and I would see these logs:
```
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:46.867 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:46.867 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:47.869 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:47.869 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:48.871 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:48.871 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:49.873 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:49.873 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:50.875 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:50.875 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:51.877 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:51.877 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:52.879 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:52.879 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:53.881 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:53.881 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-1 test-sentinel-redis 8:S 15 Jun 2023 14:37:54.512 * Connecting to MASTER :6379
test-sentinel-redis-1 test-sentinel-redis 8:S 15 Jun 2023 14:37:54.512 # Unable to connect to MASTER: Invalid argument
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:54.883 * Connecting to MASTER :6379
test-sentinel-redis-0 test-sentinel-redis 8:S 15 Jun 2023 14:37:54.883 # Unable to connect to MASTER: Invalid argument
```

Running redis-cli info on one of the slaves:
```
root@test-sentinel-redis-0:/data# redis-cli
127.0.0.1:6379> info Replication
# Replication
role:slave
master_host:
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_read_repl_offset:0
slave_repl_offset:0
master_link_down_since_seconds:-1
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:c6c32fbe5260385663832cc0018538b78636dd6b
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
```

Running redis-cli info on the master:
```
root@test-sentinel-redis-2:/data# redis-cli
127.0.0.1:6379> info Replication
# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:541d07b48b19e68a56530cc0b3aee1cb096937e5
master_replid2:003e8e82cfe53ec5e7286432d7a9919254ffcaa0
master_repl_offset:61464
second_repl_offset:53029
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:41179
repl_backlog_histlen:20286
127.0.0.1:6379>
```
