### ISSUE TITLE
Redis Replication with volume mount adding non-existing mountPath 'node-conf'

### ISSUE THREAD

**Issue by omrirosner-clx** [OT-CONTAINER-KIT/redis-operator#524]
**What version of redis operator are you using?**

redis-operator version: v0.15.0

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/arm64"}

</pre></details>

**What did you do?**

Tried to add a persistent disk to redis replication.

**What did you expect to see?**
StatefulSet created successfully with the correct volumes configured 

**What did you see instead?**
The operator added an unwanted, non-existing volume `node-conf`

```
 volumeMounts:
        - mountPath: /node-conf
          name: node-conf
        - mountPath: /data
          name: test-sentinel-redis
  env:
        - name: PERSISTENCE_ENABLED
          value: "true"
        - name: REDIS_ADDR
          value: redis://localhost:6379
        - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
          value: "true"
        - name: SERVER_MODE
          value: replication
        - name: SETUP_MODE
          value: replication
```
