### ISSUE TITLE
Redis Sentinel Exporter uses wrong port in Env Vars

### ISSUE THREAD

**Issue by omrirosner-clx** [OT-CONTAINER-KIT/redis-operator#525]
**What version of redis operator are you using?**

redis-operator version: v0.14.0

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/arm64"}
</pre></details>

**What did you do?**
Tried to get metrics from Redis Sentinel instance.

**What did you expect to see?**
Sentinel metrics in our prometheus

**What did you see instead?**

Seems like the exporter is configured incorrectly. When looking at the sentinel exporter, the env vars are:
```
- env:
        - name: REDIS_ADDR
          value: redis://localhost:6379
        - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
          value: "true"
        - name: SERVER_MODE
          value: sentinel
        - name: SETUP_MODE
          value: sentinel
```

the redis_addr is wrong and I can't manually override it in the custom resource as well.
I believe this is the reason I can't see any metrics, as the redis-cli info command would fail unless the port is specified, which I don't think the exporter does.
