### ISSUE TITLE
Redis Replication service pointing to read-only replica

### ISSUE THREAD

**Issue by diptripa** [OT-CONTAINER-KIT/redis-operator#629]
**What version of redis operator are you using?**

redis-operator version: 0.15

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
1.25.11

</pre></details>

**What did you do?**
1. Created redis-replication using this manifest:
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisReplication
metadata:
  name: redis-replication
#  annotations:
#    redis.opstreelabs.in/skip-reconcile: "true"
spec:
  clusterSize: 5
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: basic-nfs-rwx-retain
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
    # env:
    # - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
    #   value: "true"
  securityContext:
    runAsUser: 1000 
```

2. Changed some parameters like storage requests and cpu, memory requests.
3. Connected to service redis-replication:6379 from app.

**What did you expect to see?**
That it is serving the cache without any issues.

**What did you see instead?**

```shell
15
You can't write against a read only replica.
14
200
13
You can't write against a read only replica.
12
200
11
You can't write against a read only replica.
10
200
9
You can't write against a read only replica.
```
