### ISSUE TITLE
Redis Sentinel not running with password setup

### ISSUE THREAD

**Issue by hoanbc** [OT-CONTAINER-KIT/redis-operator#637]
Hi All,

I did install redis-operator.v0.15.0 on Red Hat OpenShift Operator Hub. With setup redisreplication + redissentinel without password anything working normal. 
Today i need setup auth for setup redisreplication + redissentinel but it not working. Sentinal status show down
![image](https://github.com/OT-CONTAINER-KIT/redis-operator/assets/26288807/8a2955fd-2585-4449-9f02-fed36844960a)

# Image use
```yml
Image redis: quay.io/opstree/redis:v7.0.5
Image sentinel: quay.io/opstree/redis-sentinel:v7.0.11
```
# File config redisreplication
```yml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisReplication
metadata:
  name: redis-replication
  namespace: testvn-redis
spec:
  clusterSize: 3
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v7.0.5'
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: redis-password
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
    updateStrategy: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  redisExporter:
    enabled: true
    env:
      - name: TZ
        value: Asia/Ho_Chi_Minh
    image: 'quay.io/opstree/redis-exporter:v1.44.0'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  securityContext:
    runAsUser: 1000
  serviceAccountName: redis-operator
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: thin-csi
```
# File config redissentinel
```yml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisSentinel
metadata:
  name: redis-sentinel
  namespace: testvn-redis
spec:
  clusterSize: 3
  kubernetesConfig:
    image: 'quay.io/opstree/redis-sentinel:v7.0.11'
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: redis-password
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    updateStrategy: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  redisExporter:
    enabled: true
    env:
      - name: TZ
        value: Asia/Ho_Chi_Minh
    image: 'quay.io/opstree/redis-exporter:v1.44.0'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisSentinelConfig:
    downAfterMilliseconds: '30000'
    failoverTimeout: '180000'
    masterGroupName: myMaster
    parallelSyncs: '1'
    quorum: '2'
    redisPort: '6379'
    redisReplicationName: redis-replication
  securityContext:
    runAsUser: 1000
  serviceAccountName: redis-operator
```
# Secret
```yml
kind: Secret
apiVersion: v1
metadata:
  name: redis-password
  namespace: testvn-redis
data:
  password: YWJjMTIz
type: Opaque
```
