### ISSUE TITLE
Eliminate divisive terminology

### ISSUE THREAD

**Issue by javajon** [OT-CONTAINER-KIT/redis-operator#66]
Example:
```
 master:
    service:
      type: NodePort
    redisConfig: {}
  slave:
    service:
      type: ClusterIP
    redisConfig: {}
```
[CNCF Inclusive Naming Initiative provides framework to eliminate divisive terminology in code](https://siliconangle.com/2020/11/18/cncf-inclusive-naming-initiative-provides-framework-to-eliminate-divisive-terminology-in-code-kubecon/)

[Inclusive Naming Initiative](https://inclusivenaming.org/)
