### ISSUE TITLE
Openshift Operator not deploying

### ISSUE THREAD

**Issue by d4fseeker** [OT-CONTAINER-KIT/redis-operator#70]
The Redis Operator as available in the Operatorhub for Openshift 4.7 does not install by default due to OOM on the redis-operator pod. It seems the default values are too low, when modifying it deploys seemingly correctly:

First I  modify the Operator YAML to include
```
spec:
  containers:
    - resources:
        limits:
          cpu: 500m
          memory: 200Mi
```

Then I delete the Workload->ReplicaSets and let the operator re-create them with the updated resources.
The operator then deploys without additional errors.
