### ISSUE TITLE
RedisCluster Creation time facing issue.

### ISSUE THREAD

**Issue by syslab007** [OT-CONTAINER-KIT/redis-operator#714]
**Describe your question**
I have setup redis operator success , then after I have install redis cluster via helm chart but facing issue?

**What version of redis-operator are you using?**

redis-operator version: 0.15.9

I have attach logs of pod .
Defaulted container "redis-cluster-leader" out of: redis-cluster-leader, redis-exporter
mkdir: can't create directory '/node-conf': Permission denied
Redis is running without password which is not recommended
sed: /node-conf/nodes.conf: No such file or directory
Running without TLS mode
ACL_MODE is not true, skipping ACL file modification
Starting redis service in cluster mode.....
12:C 30 Nov 2023 09:29:33.664 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
12:C 30 Nov 2023 09:29:33.664 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=12, just started
12:C 30 Nov 2023 09:29:33.664 # Configuration loaded
12:M 30 Nov 2023 09:29:33.665 * monotonic clock: POSIX clock_gettime
12:M 30 Nov 2023 09:29:33.666 # Can't open /node-conf/nodes.conf in order to acquire a lock: No such file or directory

**Comment by shubham-cmyk** [comment]
I have to investigate this but this error is related to the `securityContext`

**Comment by arusa** [comment]
I have the same issue. Just freshly installed the redis-operator using helm and created a new redis-cluster. It only created leader-0 which is hanging in "CrashLoopBackOff" and the same error message message in the container logs:

```
Can't open /node-conf/nodes.conf in order to acquire a lock: No such file or directory
```

**Comment by arusa** [comment]
For me this solved the problem:

```yaml
nodeConfVolume: true
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```

As seen in this template: https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/v1beta2/redis-cluster.yaml

**Comment by teocns** [comment]
> For me this solved the problem:
> 
> ```yaml
>     nodeConfVolume: true
>     nodeConfVolumeClaimTemplate:
>       spec:
>         accessModes: ["ReadWriteOnce"]
>         resources:
>           requests:
>             storage: 1Gi
> ```
> 
> As seen in this template: https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/v1beta2/redis-cluster.yaml

That, plus: 
```
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
```

**Comment by Justynooi** [comment]
Hello, I am still getting this issue and my yaml file looks like:

```
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: apps
spec:
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisLeader:
    replicas: 3
  redisFollower:
    replicas: 6
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    nodeConfVolume: true
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
```
            
  Am I missing something?
