### ISSUE TITLE
Need to expose Redis cluster to outside kubernetes cluster

### ISSUE THREAD

**Issue by ravina-c** [OT-CONTAINER-KIT/redis-operator#745]
Hi All

I want to expose the redis cluster outside K8s cluster using load balancer. In the process, I am not able to connect to all the redis nodes created when accessed from outside. It is connecting to one node at a time.

Below I have described how i tried to use Nodeport service :
I manually set the following in a config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-external-config
data:
  redis-additional.conf: |
    cluster-announce-ip <node ip>
    cluster-announce-tls-port 6379
    cluster-announce-port 0
    cluster-announce-bus-port 6380
 ``` 
   And the redis cluster yaml is :
 ```
  ---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  clusterVersion: v7
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    service:
      serviceType: NodePort
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
    readinessProbe:
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config
    readinessProbe:
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
````

**Comment by drivebyer** [comment]
try this
1. build operator from the latest code
2. apply https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/cluster.yaml

**Comment by ravina-c** [comment]
Hi @drivebyer ,
We tried as you said and now we have a node port for every Redis node. But when we tried to connect with redis from outside the cluster using redis-cli, we are not able to perform set and get operations, getting connection refused.
```
redis-cli -c -h <nodeip> -p 31164
<nodeip>:31164> set 1 1
-> Redirected to slot [9842] located at <nodeip>:32171
Could not connect to Redis at <nodeip>:32171: Connection refused
Could not connect to Redis at <nodeip>:32171: Connection refused
not connected> get 1
Could not connect to Redis at <nodeip>:32171: Connection refused
not connected>

```

Also, from within the cluster when I give keys * command, it retrieves the keys only from one node to which it is connected.
Should we add something to get all the keys stored in Redis, or is the functionality itself is to retrieve only the keys from the node to which it is connected to?

**Comment by drivebyer** [comment]
try to connect <nodeip>:32171 out of cluster, see whether it connected or not

**Comment by drivebyer** [comment]
> We tried as you said and now we have a node port for every Redis node. But when we tried to connect with redis from outside the cluster using redis-cli, we are not able to perform set and get operations, getting connection refused.
> 
> ```
> redis-cli -c -h <nodeip> -p 31164
> <nodeip>:31164> set 1 1
> -> Redirected to slot [9842] located at <nodeip>:32171
> Could not connect to Redis at <nodeip>:32171: Connection refused
> Could not connect to Redis at <nodeip>:32171: Connection refused
> not connected> get 1
> Could not connect to Redis at <nodeip>:32171: Connection refused
> not connected>
> ```

Try to connect :32171 out of cluster, see whether it connected or not

**Comment by ravina-c** [comment]
> > We tried as you said and now we have a node port for every Redis node. But when we tried to connect with redis from outside the cluster using redis-cli, we are not able to perform set and get operations, getting connection refused.
> > ```
> > redis-cli -c -h <nodeip> -p 31164
> > <nodeip>:31164> set 1 1
> > -> Redirected to slot [9842] located at <nodeip>:32171
> > Could not connect to Redis at <nodeip>:32171: Connection refused
> > Could not connect to Redis at <nodeip>:32171: Connection refused
> > not connected> get 1
> > Could not connect to Redis at <nodeip>:32171: Connection refused
> > not connected>
> > ```
> 
> Try to connect :32171 out of cluster, see whether it connected or not

For that port also, we get the same issue. 
```
redis-cli -c -h nodeip -p 32171
nodeip:32171> set 1 1
OK
nodeip:32171> get 1
"1"
nodeip:32171> set 2 2
OK
nodeip:32171> get 2
"2"
nodeip:32171> set 3 3
-> Redirected to slot [1584] located at nodeip:31164
Could not connect to Redis at nodeip:31164: Connection refused
Could not connect to Redis at nodeip:31164: Connection refused
not connected>
```

**Comment by drivebyer** [comment]
> > > We tried as you said and now we have a node port for every Redis node. But when we tried to connect with redis from outside the cluster using redis-cli, we are not able to perform set and get operations, getting connection refused.
> > > ```
> > > redis-cli -c -h <nodeip> -p 31164
> > > <nodeip>:31164> set 1 1
> > > -> Redirected to slot [9842] located at <nodeip>:32171
> > > Could not connect to Redis at <nodeip>:32171: Connection refused
> > > Could not connect to Redis at <nodeip>:32171: Connection refused
> > > not connected> get 1
> > > Could not connect to Redis at <nodeip>:32171: Connection refused
> > > not connected>
> > > ```
> > 
> > 
> > Try to connect :32171 out of cluster, see whether it connected or not
> 
> For that port also, we get the same issue.
> 
> ```
> redis-cli -c -h nodeip -p 32171
> nodeip:32171> set 1 1
> OK
> nodeip:32171> get 1
> "1"
> nodeip:32171> set 2 2
> OK
> nodeip:32171> get 2
> "2"
> nodeip:32171> set 3 3
> -> Redirected to slot [1584] located at nodeip:31164
> Could not connect to Redis at nodeip:31164: Connection refused
> Could not connect to Redis at nodeip:31164: Connection refused
> not connected>
> ```

what's the resource yaml. let me reproduce.

**Comment by ravina-c** [comment]
> > > > We tried as you said and now we have a node port for every Redis node. But when we tried to connect with redis from outside the cluster using redis-cli, we are not able to perform set and get operations, getting connection refused.
> > > > ```
> > > > redis-cli -c -h <nodeip> -p 31164
> > > > <nodeip>:31164> set 1 1
> > > > -> Redirected to slot [9842] located at <nodeip>:32171
> > > > Could not connect to Redis at <nodeip>:32171: Connection refused
> > > > Could not connect to Redis at <nodeip>:32171: Connection refused
> > > > not connected> get 1
> > > > Could not connect to Redis at <nodeip>:32171: Connection refused
> > > > not connected>
> > > > ```
> > > 
> > > 
> > > Try to connect :32171 out of cluster, see whether it connected or not
> > 
> > 
> > For that port also, we get the same issue.
> > ```
> > redis-cli -c -h nodeip -p 32171
> > nodeip:32171> set 1 1
> > OK
> > nodeip:32171> get 1
> > "1"
> > nodeip:32171> set 2 2
> > OK
> > nodeip:32171> get 2
> > "2"
> > nodeip:32171> set 3 3
> > -> Redirected to slot [1584] located at nodeip:31164
> > Could not connect to Redis at nodeip:31164: Connection refused
> > Could not connect to Redis at nodeip:31164: Connection refused
> > not connected>
> > ```
> 
> what's the resource yaml. let me reproduce.

```

apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster-v1beta2
spec:
  clusterSize: 3
  clusterVersion: v6
  persistenceEnabled: true
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  kubernetesConfig:
    service:
      serviceType: NodePort
    image: quay.io/opstree/redis:v6.2.14
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    nodeConfVolume: true
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
            
   ```
