### ISSUE TITLE
Specify the port number of the NodePort of Redis

### ISSUE THREAD

**Issue by mkadokawa-idcf** [OT-CONTAINER-KIT/redis-operator#762]
**Is your feature request related to a problem? Please describe.**

Currently, it is not possible to specify the port number of the Redis NodePort.
With the default settings, a port number between 30000 and 32767 is randomly assigned.

**Describe the solution you'd like**

I want to specify the port number of the NodePort as follows.
```yaml
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis-standalone
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    service:
      serviceType: NodePort
      nodePort: 31111   # specify the NodePort number here
```

**Describe alternatives you've considered**

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/services.go#L49-L54
I would like to make the following changes to the above section.
```go
func generateServiceDef(serviceMeta metav1.ObjectMeta, epp exporterPortProvider, ownerDef metav1.OwnerReference, headless bool, serviceType string, port, nodePort int, extra ...corev1.ServicePort) *corev1.Service {
	....
	service := &corev1.Service{
		TypeMeta:   generateMetaInformation("Service", "v1"),
		ObjectMeta: serviceMeta,
		Spec: corev1.ServiceSpec{
			Type:      generateServiceType(serviceType),
			ClusterIP: "",
			Selector:  serviceMeta.GetLabels(),
			Ports: []corev1.ServicePort{
				{
					Name:       PortName,
					Port:       int32(port),
					TargetPort: intstr.FromInt(int(port)),
                                        NodePort:   int32(nodePort)   # add here
					Protocol:   corev1.ProtocolTCP,
				},
			},
		},
	}
        ....
```

**What version of redis-operator are you using?**

redis-operator version: v0.15.1

**Additional context**

The following comments are similar in intent to this issue.
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/79#issuecomment-848669389
