### ISSUE TITLE
Redis not respecting existingPasswordSecret in configuration 

### ISSUE THREAD

**Issue by jzaccone** [OT-CONTAINER-KIT/redis-operator#84]
I created a redis using the operator (using the Operators menu in OpenShift) using this yaml

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  namespace: mdsp-back-redis60
  name: redis-with-operator3
spec:
  size: 3
  master:
    redisConfig: {}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      type: ClusterIP
  mode: cluster
  global:
    image: 'quay.io/opstree/redis:v6.2'
    imagePullPolicy: IfNotPresent
    existingPasswordSecret:
      enabled: true
      name: redis-secret
      key: password
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: '100m'
        memory: 128Mi
  service:
    type: ClusterIP
  slave:
    redisConfig: {}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      type: ClusterIP
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ibmc-block-gold
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisConfig: {}
```

When I try to test the connection, it allows me to write data to redis without authenticating
```
kubectl exec -it redis-with-operator3-master-0 redis-cli
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulting container name to redis-with-operator3-master.
Use 'kubectl describe pod/redis-with-operator3-master-0 -n mdsp-back-redis60' to see all of the containers in this pod.
127.0.0.1:6379> ping
PONG
127.0.0.1:6379> incr counter
(integer) 1
```

Operator version: 0.5.0
