### ISSUE TITLE
Bug Report: Redis Pods Entering Termination Loop in redis-operator v0.17.0

### ISSUE THREAD

**Issue by wkd-woo** [OT-CONTAINER-KIT/redis-operator#932]
**Summary:**
After deploying the redis-replication Helm chart, the Redis pods continuously cycle through terminating and recreating states without any external intervention. 

This issue emerged following the release of redis-operator version v0.17.0 and persists irrespective of the Redis image version used. 
Consequently, the redis-operator fails to reconcile properly, compromising the High Availability (HA) of the replication setup.

**What version of redis operator are you using?**
redis-operator version: `v0.17.0`
redis version: `v7.0.12`, `v7.2.3`

**Does this issue reproduce with the latest release?**
Yes, it's the latest released version.

**What operating system and processor architecture are you using (`kubectl version`)?**
ubuntu22, linux/amd64

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6
</pre></details>

Steps to Reproduce:

1. Deploy the redis-replication Helm chart.
2. Observe the creation of the redis-replication StatefulSet and its associated pods.
3. Note that the pods enter a continuous cycle of states: Terminating -> ContainerCreating -> Running -> Terminating.

**Observed Behavior** 
- Redis pods are continuously deleted and recreated without any manual intervention.
- This cycle severely impacts the stability of the Redis replication setup.
- The redis-operator does not reconcile the state of the Redis cluster correctly.
- High Availability (HA) of the Redis replication is broken due to this issue.

**What did you do?**
I just deploy redis replication via helm-chart

```
helm install redis-replication helm/charts/common/redis-replication -f workspace/development/manifests/ke/replication.yaml --debug

client.go:142: [debug] creating 3 resource(s)
NAME: redis-replication
LAST DEPLOYED: Fri May 17 14:56:13 2024
NAMESPACE: jude
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

and following below is the manifest I'm using
```
---
redisReplication:
  name: ""
  clusterSize: 3
  image: <REGISTRY_URL>/redis
  tag: v7.0.12
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 101m
      memory: 3Gi
    limits:
      cpu: 101m
      memory: 3Gi
  ignoreAnnotations: []

# Overwite name for resources
# name: ""

labels:
  topology: sentinel
  dbservice: redis
  servicename: jude-replication

externalConfig:
  enabled: true
  data: |
      <CONFIGURATIONS>

externalService:
  enabled: true
  serviceType: NodePort
  port: 6379

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  image: <REGISTRY_URL>/redis-exporter
  tag: v1.44.0
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  env: []

initContainer:
  enabled: false
  image: ""
  imagePullPolicy: "IfNotPresent"
  resources: {}
  env: []
  command: []
  args: []

sidecars:
  name: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  env: []

priorityClassName: ""

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
  topology: sentinel

storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: csi-cinder-sc-delete
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

securityContext: {}

affinity: {}

tolerations: []

TLS:
  ca: ca.key
  cert: tls.crt
  key: tls.key
  secret:
    secretName: ""

acl:
  secret:
    # secretName: "redis-acl"

env: []
```

**What did you see instead?**
```
$ k get all
NAME                      READY   STATUS        RESTARTS   AGE
pod/redis-replication-0   2/2     Running       0          5m37s
pod/redis-replication-1   2/2     Terminating   0          49s
pod/redis-replication-2   2/2     Running       0          8s
```
- Pod `redis-replication-1` is in Terminating state while others are running.

```
$ k exec -it pod/redis-replication-0 -- redis-cli ROLE
Defaulted container "redis-replication" out of: redis-replication, redis-exporter
1) "master"
2) (integer) 476
3) 1) 1) "192.168.43.204"
      2) "6379"
      3) "476"
   2) 1) "192.168.251.42"
      2) "6379"
      3) "476"
```

- `redis-replication-0` is the master, with `redis-replication-2` as its slave.

```
$ k get all
NAME                      READY   STATUS        RESTARTS   AGE
pod/redis-replication-0   2/2     Running       0          6m59s
pod/redis-replication-1   2/2     Running       0          18s
pod/redis-replication-2   2/2     Terminating   0          90s
```
- Now, redis-replication-2 is in Terminating state, while redis-replication-1 is back to running.

```
$ k exec -it pod/redis-replication-0 -- redis-cli ROLE
Defaulted container "redis-replication" out of: redis-replication, redis-exporter
1) "master"
2) (integer) 546
3) 1) 1) "192.168.251.43"
      2) "6379"
      3) "546"
```
- `redis-replication-0` remains the master, with updated replication state.

```
$ k get all
NAME                      READY   STATUS        RESTARTS   AGE
pod/redis-replication-0   2/2     Running       0          8m22s
pod/redis-replication-1   2/2     Terminating   0          101s
pod/redis-replication-2   2/2     Running       0          24s
```
- `redis-replication-1` enters Terminating state again, continuing the cycle.

```
$ k exec -it pod/redis-replication-0 -- redis-cli ROLE
Defaulted container "redis-replication" out of: redis-replication, redis-exporter
1) "master"
2) (integer) 644
3) 1) 1) "192.168.43.201"
      2) "6379"
      3) "644"
```
- Master role remains with `redis-replication-0`, updating its replication state.Further 

```
$ k get all 
NAME                      READY   STATUS        RESTARTS   AGE
pod/redis-replication-0   2/2     Terminating   0          8m59s
pod/redis-replication-1   2/2     Running       0          23s
pod/redis-replication-2   2/2     Running       0          61s
```
- Now `redis-replication-0` enters Terminating state.

**Latest Observation:**
```
$ k get all
NAME                      READY   STATUS              RESTARTS   AGE
pod/redis-replication-0   0/2     ContainerCreating   0          5s
pod/redis-replication-1   2/2     Running             0          40s
pod/redis-replication-2   2/2     Running             0          78s
```
`redis-replication-0` is recreated, now in ContainerCreating state.

```
$ k exec -it pod/redis-replication-1 -- redis-cli ROLE
Defaulted container "redis-replication" out of: redis-replication, redis-exporter
1) "slave"
2) "192.168.52.204"
3) (integer) 6379
4) "connecting"
5) (integer) -1

$ k exec -it pod/redis-replication-2 -- redis-cli ROLE
Defaulted container "redis-replication" out of: redis-replication, redis-exporter
1) "slave"
2) "192.168.52.204"
3) (integer) 6379
4) "connecting"
5) (integer) -1
```
- Both `redis-replication-1` and `redis-replication-2` are in slave state but show connecting status, unable to properly connect to the master.
-
