### ISSUE TITLE
Passing custom metadata to redis pods

### ISSUE THREAD

**Issue by oliveratprimer** [OT-CONTAINER-KIT/redis-operator#95]
What would be the right way to pass custom labels and annotations to redis pods? Adding them to the [metadata section](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/redis-cluster-example.yaml#L4) in the manifest seems to only add it to the redis object and not the pod.

**Comment by fabio-pardo** [comment]
Has there update with this?

**Comment by davidcollom** [comment]
Seams a reasonable ask.

What would your expected API Look like for a Redis/RedisCluster Resource?

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  [...SNIP...]
  labels:
    labelkey: value
  annotations:
    annotations: value
```


Or were you thinking something a little more simplistic in that all labels/annotations from the Redis/RedisCluster resource are reflected on the Statefulset/Pods:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
  labels:
    labelkey: labelvalue
  annotations:
    annotation: value
spec:
  clusterSize: 3
  [...SNIP...]
```
