### ISSUE TITLE
Mismatch metadata / service selector

### ISSUE THREAD

**Issue by CanKattwinkel** [OT-CONTAINER-KIT/redis-operator#98]
We are leveraging your operator to maintain a small standalone Redis instance, however, since yesterday we are seeing issues. I have realized that the service selector does not match the pods metadata anymore. We used the default values for the helm chart to deploy the operator and then applied a standalone instance to reproduce:

The pod looks like this

```
apiVersion: v1
kind: Pod
metadata:
  generateName: redis3-standalone-
  labels:
    app: redis3-standalone
    role: standalone
    statefulset.kubernetes.io/pod-name: redis3-standalone-0
```

And the associated service specifies the additional field `redis: monitor` in the sector property.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
    redis.opstreelabs.in: "true"
  labels:
    app: redis3-standalone
    redis: monitor
    role: standalone
  name: redis3
spec:
  clusterIP: xx.xx.x.xx
  ports:
  - name: redis3-standalone
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis3-standalone
    redis: monitor
    role: standalone
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**So the problem is:** Redis cant be reached as the service is not connecting to the pod.

I verified this by deployed a new service that lacked the `redis` key in the selector and verified that I can then port forward into redis using the service. I'm not sure where the redis field originates from and if I patch it, the operator would remove my changes.
